namespace Building.Help.Panel
{
    partial class CtlTotal
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CtlTotal));
            DevExpress.XtraEditors.TileItemElement tileItemElement1 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement2 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame1 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement3 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement4 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame2 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement5 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement6 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement7 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement8 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame3 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement9 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame4 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement10 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement11 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement12 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement13 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame5 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement14 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame6 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement15 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement16 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement17 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement18 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement19 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement20 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement21 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement22 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame7 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement23 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement24 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame8 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement25 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement26 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame9 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement27 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement28 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame10 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement29 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement30 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement31 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement32 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement33 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement34 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement35 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement36 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement37 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement38 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement39 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement40 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement41 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement42 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement43 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement44 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement45 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement46 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame11 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement47 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement48 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame12 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement49 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement50 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement51 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement52 = new DevExpress.XtraEditors.TileItemElement();
            this.tileControl1 = new DevExpress.XtraEditors.TileControl();
            this.tileGroup2 = new DevExpress.XtraEditors.TileGroup();
            this.tileItem13 = new DevExpress.XtraEditors.TileItem();
            this.tileItem1 = new DevExpress.XtraEditors.TileItem();
            this.tileItem2 = new DevExpress.XtraEditors.TileItem();
            this.tileItem4 = new DevExpress.XtraEditors.TileItem();
            this.tileGroup3 = new DevExpress.XtraEditors.TileGroup();
            this.tileItem5 = new DevExpress.XtraEditors.TileItem();
            this.tileItem3 = new DevExpress.XtraEditors.TileItem();
            this.tileItem12 = new DevExpress.XtraEditors.TileItem();
            this.tileGroup4 = new DevExpress.XtraEditors.TileGroup();
            this.tileItem6 = new DevExpress.XtraEditors.TileItem();
            this.tileItem9 = new DevExpress.XtraEditors.TileItem();
            this.tileItem7 = new DevExpress.XtraEditors.TileItem();
            this.tileItem8 = new DevExpress.XtraEditors.TileItem();
            this.tileItem15 = new DevExpress.XtraEditors.TileItem();
            this.tileItem10 = new DevExpress.XtraEditors.TileItem();
            this.tileItem11 = new DevExpress.XtraEditors.TileItem();
            this.SuspendLayout();
            // 
            // tileControl1
            // 
            this.tileControl1.AllowDrag = false;
            this.tileControl1.AllowDragTilesBetweenGroups = false;
            this.tileControl1.AllowItemHover = true;
            this.tileControl1.AppearanceGroupText.ForeColor = System.Drawing.Color.White;
            this.tileControl1.AppearanceGroupText.Options.UseForeColor = true;
            this.tileControl1.AppearanceItem.Normal.ForeColor = System.Drawing.Color.White;
            this.tileControl1.AppearanceItem.Normal.Options.UseForeColor = true;
            this.tileControl1.AppearanceText.ForeColor = System.Drawing.Color.White;
            this.tileControl1.AppearanceText.Options.UseForeColor = true;
            this.tileControl1.AppearanceText.Options.UseTextOptions = true;
            this.tileControl1.AppearanceText.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.tileControl1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(130)))), ((int)(((byte)(248)))));
            this.tileControl1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tileControl1.BackgroundImage")));
            this.tileControl1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tileControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tileControl1.Groups.Add(this.tileGroup2);
            this.tileControl1.Groups.Add(this.tileGroup3);
            this.tileControl1.Groups.Add(this.tileGroup4);
            this.tileControl1.ItemBorderVisibility = DevExpress.XtraEditors.TileItemBorderVisibility.Never;
            this.tileControl1.Location = new System.Drawing.Point(0, 0);
            this.tileControl1.MaxId = 37;
            this.tileControl1.Name = "tileControl1";
            this.tileControl1.ShowGroupText = true;
            this.tileControl1.ShowText = true;
            this.tileControl1.Size = new System.Drawing.Size(667, 435);
            this.tileControl1.TabIndex = 1;
            this.tileControl1.Text = "Hướng dẫn sử dụng Phần mềm Building";
            this.tileControl1.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileControl1_ItemClick);
            // 
            // tileGroup2
            // 
            this.tileGroup2.Items.Add(this.tileItem13);
            this.tileGroup2.Items.Add(this.tileItem1);
            this.tileGroup2.Items.Add(this.tileItem2);
            this.tileGroup2.Items.Add(this.tileItem4);
            this.tileGroup2.Name = "tileGroup2";
            this.tileGroup2.Text = "Hệ thống";
            // 
            // tileItem13
            // 
            this.tileItem13.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(144)))), ((int)(((byte)(163)))));
            this.tileItem13.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem13.CurrentFrameIndex = 1;
            tileItemElement1.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image")));
            tileItemElement1.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement1.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement1.ImageOptions.ImageSize = new System.Drawing.Size(270, 150);
            tileItemElement2.Text = "Hướng dẫn sử dụng";
            tileItemElement2.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItem13.Elements.Add(tileItemElement1);
            this.tileItem13.Elements.Add(tileItemElement2);
            tileItemFrame1.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement3.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image1")));
            tileItemElement3.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement3.ImageOptions.ImageLocation = new System.Drawing.Point(70, 60);
            tileItemElement3.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement3.ImageOptions.ImageSize = new System.Drawing.Size(100, 100);
            tileItemElement4.Text = "Hướng dẫn sử dụng";
            tileItemElement4.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileItemFrame1.Elements.Add(tileItemElement3);
            tileItemFrame1.Elements.Add(tileItemElement4);
            tileItemFrame1.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame1.Image")));
            tileItemFrame2.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement5.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image2")));
            tileItemElement5.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement5.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement5.ImageOptions.ImageSize = new System.Drawing.Size(270, 150);
            tileItemElement6.Text = "Hướng dẫn sử dụng";
            tileItemElement6.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileItemFrame2.Elements.Add(tileItemElement5);
            tileItemFrame2.Elements.Add(tileItemElement6);
            tileItemFrame2.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame2.Image")));
            this.tileItem13.Frames.Add(tileItemFrame1);
            this.tileItem13.Frames.Add(tileItemFrame2);
            this.tileItem13.Id = 30;
            this.tileItem13.ItemSize = DevExpress.XtraEditors.TileItemSize.Large;
            this.tileItem13.Name = "tileItem13";
            // 
            // tileItem1
            // 
            this.tileItem1.AppearanceItem.Normal.BackColor = System.Drawing.SystemColors.Highlight;
            this.tileItem1.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem1.CurrentFrameIndex = 1;
            tileItemElement7.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement7.Appearance.Hovered.Options.UseFont = true;
            tileItemElement7.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement7.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement7.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement7.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement7.Appearance.Normal.Options.UseFont = true;
            tileItemElement7.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement7.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement7.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement7.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement7.Appearance.Selected.Options.UseFont = true;
            tileItemElement7.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement7.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement7.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement7.Text = "System";
            tileItemElement7.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement7.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement8.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement8.Appearance.Hovered.Options.UseFont = true;
            tileItemElement8.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement8.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement8.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement8.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement8.Appearance.Normal.Options.UseFont = true;
            tileItemElement8.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement8.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement8.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement8.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement8.Appearance.Selected.Options.UseFont = true;
            tileItemElement8.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement8.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement8.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement8.Text = "Cấu hình hệ thống, ngôn ngữ, FTP, giao diện";
            tileItemElement8.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement8.TextLocation = new System.Drawing.Point(4, 27);
            this.tileItem1.Elements.Add(tileItemElement7);
            this.tileItem1.Elements.Add(tileItemElement8);
            tileItemFrame3.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement9.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image3")));
            tileItemElement9.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement9.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement9.ImageOptions.ImageSize = new System.Drawing.Size(50, 50);
            tileItemFrame3.Elements.Add(tileItemElement9);
            tileItemFrame3.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame3.Image")));
            tileItemFrame4.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement10.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement10.Appearance.Hovered.Options.UseFont = true;
            tileItemElement10.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement10.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement10.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement10.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement10.Appearance.Normal.Options.UseFont = true;
            tileItemElement10.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement10.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement10.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement10.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement10.Appearance.Selected.Options.UseFont = true;
            tileItemElement10.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement10.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement10.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement10.Text = "System";
            tileItemElement10.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement10.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement11.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement11.Appearance.Hovered.Options.UseFont = true;
            tileItemElement11.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement11.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement11.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement11.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement11.Appearance.Normal.Options.UseFont = true;
            tileItemElement11.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement11.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement11.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement11.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement11.Appearance.Selected.Options.UseFont = true;
            tileItemElement11.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement11.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement11.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement11.Text = "Cấu hình hệ thống, ngôn ngữ, FTP, giao diện";
            tileItemElement11.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement11.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame4.Elements.Add(tileItemElement10);
            tileItemFrame4.Elements.Add(tileItemElement11);
            this.tileItem1.Frames.Add(tileItemFrame3);
            this.tileItem1.Frames.Add(tileItemFrame4);
            this.tileItem1.Id = 14;
            this.tileItem1.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem1.Name = "tileItem1";
            // 
            // tileItem2
            // 
            this.tileItem2.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.tileItem2.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem2.CurrentFrameIndex = 1;
            tileItemElement12.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement12.Appearance.Hovered.Options.UseFont = true;
            tileItemElement12.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement12.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement12.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement12.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement12.Appearance.Normal.Options.UseFont = true;
            tileItemElement12.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement12.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement12.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement12.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement12.Appearance.Selected.Options.UseFont = true;
            tileItemElement12.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement12.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement12.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement12.Text = "Tài liệu";
            tileItemElement12.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement12.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement13.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement13.Appearance.Hovered.Options.UseFont = true;
            tileItemElement13.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement13.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement13.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement13.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement13.Appearance.Normal.Options.UseFont = true;
            tileItemElement13.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement13.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement13.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement13.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement13.Appearance.Selected.Options.UseFont = true;
            tileItemElement13.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement13.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement13.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement13.Text = "Cấu hình nhóm biểu mẫu, trường trộn, tài liệu, biểu mẫu ";
            tileItemElement13.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement13.TextLocation = new System.Drawing.Point(4, 27);
            this.tileItem2.Elements.Add(tileItemElement12);
            this.tileItem2.Elements.Add(tileItemElement13);
            tileItemFrame5.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement14.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image4")));
            tileItemElement14.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement14.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement14.ImageOptions.ImageSize = new System.Drawing.Size(50, 50);
            tileItemFrame5.Elements.Add(tileItemElement14);
            tileItemFrame5.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame5.Image")));
            tileItemFrame6.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement15.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement15.Appearance.Hovered.Options.UseFont = true;
            tileItemElement15.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement15.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement15.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement15.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement15.Appearance.Normal.Options.UseFont = true;
            tileItemElement15.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement15.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement15.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement15.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement15.Appearance.Selected.Options.UseFont = true;
            tileItemElement15.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement15.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement15.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement15.Text = "Tài liệu";
            tileItemElement15.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement15.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement16.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement16.Appearance.Hovered.Options.UseFont = true;
            tileItemElement16.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement16.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement16.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement16.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement16.Appearance.Normal.Options.UseFont = true;
            tileItemElement16.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement16.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement16.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement16.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement16.Appearance.Selected.Options.UseFont = true;
            tileItemElement16.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement16.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement16.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement16.Text = "Cấu hình nhóm biểu mẫu, trường trộn, tài liệu, biểu mẫu ";
            tileItemElement16.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement16.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame6.Elements.Add(tileItemElement15);
            tileItemFrame6.Elements.Add(tileItemElement16);
            this.tileItem2.Frames.Add(tileItemFrame5);
            this.tileItem2.Frames.Add(tileItemFrame6);
            this.tileItem2.Id = 19;
            this.tileItem2.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem2.Name = "tileItem2";
            // 
            // tileItem4
            // 
            this.tileItem4.AppearanceItem.Normal.BackColor = System.Drawing.SystemColors.MenuHighlight;
            this.tileItem4.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement17.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement17.Appearance.Hovered.Options.UseFont = true;
            tileItemElement17.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement17.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement17.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement17.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement17.Appearance.Normal.Options.UseFont = true;
            tileItemElement17.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement17.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement17.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement17.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement17.Appearance.Selected.Options.UseFont = true;
            tileItemElement17.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement17.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement17.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement17.MaxWidth = 170;
            tileItemElement17.Text = "Dự án";
            tileItemElement17.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement17.TextLocation = new System.Drawing.Point(3, 0);
            tileItemElement18.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement18.Appearance.Hovered.Options.UseFont = true;
            tileItemElement18.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement18.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement18.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement18.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement18.Appearance.Normal.Options.UseFont = true;
            tileItemElement18.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement18.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement18.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement18.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement18.Appearance.Selected.Options.UseFont = true;
            tileItemElement18.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement18.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement18.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement18.MaxWidth = 160;
            tileItemElement18.Text = "Khai báo, cài đặt các căn hộ, kinh phí dự trù";
            tileItemElement18.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement18.TextLocation = new System.Drawing.Point(3, 27);
            tileItemElement19.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image5")));
            tileItemElement19.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement19.ImageOptions.ImageLocation = new System.Drawing.Point(172, 8);
            tileItemElement19.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement19.ImageOptions.ImageSize = new System.Drawing.Size(48, 48);
            tileItemElement20.AnchorElementIndex = 1;
            tileItemElement20.AnchorIndent = 25;
            tileItemElement20.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement20.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement20.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement20.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement20.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement20.Height = 20;
            tileItemElement20.StretchHorizontal = true;
            tileItemElement20.Text = "Thông tin dự án";
            this.tileItem4.Elements.Add(tileItemElement17);
            this.tileItem4.Elements.Add(tileItemElement18);
            this.tileItem4.Elements.Add(tileItemElement19);
            this.tileItem4.Elements.Add(tileItemElement20);
            this.tileItem4.Id = 6;
            this.tileItem4.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem4.Name = "tileItem4";
            // 
            // tileGroup3
            // 
            this.tileGroup3.Items.Add(this.tileItem5);
            this.tileGroup3.Items.Add(this.tileItem3);
            this.tileGroup3.Items.Add(this.tileItem12);
            this.tileGroup3.Name = "tileGroup3";
            this.tileGroup3.Text = "Dự án";
            // 
            // tileItem5
            // 
            this.tileItem5.CurrentFrameIndex = 3;
            tileItemElement21.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image6")));
            tileItemElement21.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement21.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement21.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement22.AnchorIndent = 25;
            tileItemElement22.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement22.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement22.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement22.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement22.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement22.Height = 20;
            tileItemElement22.StretchHorizontal = true;
            tileItemElement22.Text = "Quản lý mặt bằng";
            tileItemElement22.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            this.tileItem5.Elements.Add(tileItemElement21);
            this.tileItem5.Elements.Add(tileItemElement22);
            tileItemFrame7.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement23.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image7")));
            tileItemElement23.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement23.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement23.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement23.Text = "";
            tileItemElement24.AnchorIndent = 25;
            tileItemElement24.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement24.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement24.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement24.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement24.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement24.Height = 20;
            tileItemElement24.StretchHorizontal = true;
            tileItemElement24.Text = "Quản lý căn hộ";
            tileItemElement24.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemFrame7.Elements.Add(tileItemElement23);
            tileItemFrame7.Elements.Add(tileItemElement24);
            tileItemFrame7.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame7.Image")));
            tileItemFrame8.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement25.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image8")));
            tileItemElement25.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement25.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement25.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement25.Text = "";
            tileItemElement26.AnchorAlignment = DevExpress.Utils.AnchorAlignment.Left;
            tileItemElement26.AnchorIndent = 25;
            tileItemElement26.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement26.AnimateTransition = DevExpress.Utils.DefaultBoolean.True;
            tileItemElement26.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement26.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement26.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement26.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement26.Height = 20;
            tileItemElement26.StretchHorizontal = true;
            tileItemElement26.Text = "Quản lý mặt bằng";
            tileItemElement26.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement26.UseImageInTransition = false;
            tileItemFrame8.Elements.Add(tileItemElement25);
            tileItemFrame8.Elements.Add(tileItemElement26);
            tileItemFrame8.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame8.Image")));
            tileItemFrame9.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement27.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image9")));
            tileItemElement27.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement27.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement27.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement28.AnchorIndent = 25;
            tileItemElement28.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement28.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement28.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement28.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement28.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement28.Height = 20;
            tileItemElement28.StretchHorizontal = true;
            tileItemElement28.Text = "Quản lý mặt bằng";
            tileItemElement28.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemFrame9.Elements.Add(tileItemElement27);
            tileItemFrame9.Elements.Add(tileItemElement28);
            tileItemFrame9.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame9.Image")));
            tileItemFrame10.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement29.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image10")));
            tileItemElement29.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement29.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement29.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement30.AnchorIndent = 25;
            tileItemElement30.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement30.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement30.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement30.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement30.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement30.Height = 20;
            tileItemElement30.StretchHorizontal = true;
            tileItemElement30.Text = "Quản lý mặt bằng";
            tileItemElement30.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemFrame10.Elements.Add(tileItemElement29);
            tileItemFrame10.Elements.Add(tileItemElement30);
            tileItemFrame10.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame10.Image")));
            this.tileItem5.Frames.Add(tileItemFrame7);
            this.tileItem5.Frames.Add(tileItemFrame8);
            this.tileItem5.Frames.Add(tileItemFrame9);
            this.tileItem5.Frames.Add(tileItemFrame10);
            this.tileItem5.Id = 7;
            this.tileItem5.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem5.Name = "tileItem5";
            // 
            // tileItem3
            // 
            this.tileItem3.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.tileItem3.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement31.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement31.Appearance.Hovered.Options.UseFont = true;
            tileItemElement31.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement31.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement31.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement31.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement31.Appearance.Normal.Options.UseFont = true;
            tileItemElement31.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement31.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement31.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement31.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement31.Appearance.Selected.Options.UseFont = true;
            tileItemElement31.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement31.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement31.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement31.MaxWidth = 160;
            tileItemElement31.Text = "Phân quyền";
            tileItemElement31.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement31.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement32.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement32.Appearance.Hovered.Options.UseFont = true;
            tileItemElement32.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement32.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement32.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement32.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement32.Appearance.Normal.Options.UseFont = true;
            tileItemElement32.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement32.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement32.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement32.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement32.Appearance.Selected.Options.UseFont = true;
            tileItemElement32.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement32.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement32.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement32.MaxWidth = 160;
            tileItemElement32.Text = "Cài đặt phân quyền nhân viên, biểu đồ main";
            tileItemElement32.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement32.TextLocation = new System.Drawing.Point(75, 27);
            tileItemElement33.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image11")));
            tileItemElement33.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement33.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement33.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement33.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            this.tileItem3.Elements.Add(tileItemElement31);
            this.tileItem3.Elements.Add(tileItemElement32);
            this.tileItem3.Elements.Add(tileItemElement33);
            this.tileItem3.Id = 20;
            this.tileItem3.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem3.Name = "tileItem3";
            // 
            // tileItem12
            // 
            this.tileItem12.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(181)))), ((int)(((byte)(29)))), ((int)(((byte)(67)))));
            this.tileItem12.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement34.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement34.Appearance.Hovered.Options.UseFont = true;
            tileItemElement34.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement34.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement34.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement34.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement34.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement34.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement34.Appearance.Normal.Options.UseFont = true;
            tileItemElement34.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement34.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement34.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement34.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement34.Appearance.Selected.Options.UseFont = true;
            tileItemElement34.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement34.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement34.Height = 20;
            tileItemElement34.StretchHorizontal = true;
            tileItemElement34.Text = "Kinh phí dự trù";
            tileItemElement34.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement34.TextLocation = new System.Drawing.Point(3, 75);
            tileItemElement35.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image12")));
            tileItemElement35.ImageOptions.ImageLocation = new System.Drawing.Point(90, -40);
            tileItemElement35.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement35.ImageOptions.ImageSize = new System.Drawing.Size(50, 50);
            this.tileItem12.Elements.Add(tileItemElement34);
            this.tileItem12.Elements.Add(tileItemElement35);
            this.tileItem12.Id = 29;
            this.tileItem12.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem12.Name = "tileItem12";
            // 
            // tileGroup4
            // 
            this.tileGroup4.Items.Add(this.tileItem6);
            this.tileGroup4.Items.Add(this.tileItem9);
            this.tileGroup4.Items.Add(this.tileItem7);
            this.tileGroup4.Items.Add(this.tileItem8);
            this.tileGroup4.Items.Add(this.tileItem15);
            this.tileGroup4.Items.Add(this.tileItem10);
            this.tileGroup4.Items.Add(this.tileItem11);
            this.tileGroup4.Name = "tileGroup4";
            this.tileGroup4.Text = "Khách hàng";
            // 
            // tileItem6
            // 
            this.tileItem6.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(61)))), ((int)(((byte)(186)))));
            this.tileItem6.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement36.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image13")));
            tileItemElement36.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement36.ImageOptions.ImageLocation = new System.Drawing.Point(60, 60);
            tileItemElement36.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement36.ImageOptions.ImageSize = new System.Drawing.Size(100, 100);
            tileItemElement36.ImageOptions.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.None;
            tileItemElement36.Text = "Khách hàng";
            tileItemElement36.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItem6.Elements.Add(tileItemElement36);
            this.tileItem6.Id = 8;
            this.tileItem6.ItemSize = DevExpress.XtraEditors.TileItemSize.Large;
            this.tileItem6.Name = "tileItem6";
            // 
            // tileItem9
            // 
            this.tileItem9.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(81)))), ((int)(((byte)(43)))));
            this.tileItem9.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement37.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement37.Appearance.Hovered.Options.UseFont = true;
            tileItemElement37.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement37.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement37.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement37.Appearance.Normal.Options.UseFont = true;
            tileItemElement37.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement37.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement37.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement37.Appearance.Selected.Options.UseFont = true;
            tileItemElement37.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement37.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement37.Text = "Quản lý cư dân";
            tileItemElement37.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement37.TextLocation = new System.Drawing.Point(3, 75);
            tileItemElement38.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image14")));
            tileItemElement38.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement38.ImageOptions.ImageLocation = new System.Drawing.Point(-12, -8);
            tileItemElement38.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement38.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            this.tileItem9.Elements.Add(tileItemElement37);
            this.tileItem9.Elements.Add(tileItemElement38);
            this.tileItem9.Id = 25;
            this.tileItem9.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem9.Name = "tileItem9";
            // 
            // tileItem7
            // 
            this.tileItem7.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(134)))), ((int)(((byte)(153)))));
            this.tileItem7.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement39.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement39.Appearance.Hovered.Options.UseFont = true;
            tileItemElement39.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement39.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement39.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement39.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement39.Appearance.Normal.Options.UseFont = true;
            tileItemElement39.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement39.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement39.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement39.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement39.Appearance.Selected.Options.UseFont = true;
            tileItemElement39.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement39.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement39.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement39.MaxWidth = 160;
            tileItemElement39.Text = "Yêu cầu";
            tileItemElement39.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement39.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement40.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement40.Appearance.Hovered.Options.UseFont = true;
            tileItemElement40.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement40.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement40.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement40.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement40.Appearance.Normal.Options.UseFont = true;
            tileItemElement40.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement40.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement40.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement40.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement40.Appearance.Selected.Options.UseFont = true;
            tileItemElement40.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement40.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement40.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement40.MaxWidth = 160;
            tileItemElement40.Text = "Quản lý các yêu cầu, phản hồi từ cư dân";
            tileItemElement40.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement40.TextLocation = new System.Drawing.Point(75, 27);
            tileItemElement41.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image15")));
            tileItemElement41.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement41.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement41.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement41.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            this.tileItem7.Elements.Add(tileItemElement39);
            this.tileItem7.Elements.Add(tileItemElement40);
            this.tileItem7.Elements.Add(tileItemElement41);
            this.tileItem7.Id = 31;
            this.tileItem7.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem7.Name = "tileItem7";
            // 
            // tileItem8
            // 
            this.tileItem8.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(181)))), ((int)(((byte)(29)))), ((int)(((byte)(67)))));
            this.tileItem8.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement42.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement42.Appearance.Hovered.Options.UseFont = true;
            tileItemElement42.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement42.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement42.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement42.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement42.Appearance.Normal.Options.UseFont = true;
            tileItemElement42.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement42.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement42.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement42.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement42.Appearance.Selected.Options.UseFont = true;
            tileItemElement42.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement42.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement42.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement42.MaxWidth = 170;
            tileItemElement42.Text = "Lễ tân";
            tileItemElement42.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement42.TextLocation = new System.Drawing.Point(3, 0);
            tileItemElement43.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement43.Appearance.Hovered.Options.UseFont = true;
            tileItemElement43.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement43.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement43.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement43.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement43.Appearance.Normal.Options.UseFont = true;
            tileItemElement43.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement43.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement43.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement43.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement43.Appearance.Selected.Options.UseFont = true;
            tileItemElement43.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement43.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement43.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement43.MaxWidth = 160;
            tileItemElement43.Text = "Quản lý lễ tân, khách hàng vào ra, thời gian, địa điểm";
            tileItemElement43.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement43.TextLocation = new System.Drawing.Point(3, 27);
            tileItemElement44.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image16")));
            tileItemElement44.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement44.ImageOptions.ImageLocation = new System.Drawing.Point(172, 8);
            tileItemElement44.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement44.ImageOptions.ImageSize = new System.Drawing.Size(48, 64);
            this.tileItem8.Elements.Add(tileItemElement42);
            this.tileItem8.Elements.Add(tileItemElement43);
            this.tileItem8.Elements.Add(tileItemElement44);
            this.tileItem8.Id = 32;
            this.tileItem8.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem8.Name = "tileItem8";
            // 
            // tileItem15
            // 
            this.tileItem15.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(85)))), ((int)(((byte)(189)))));
            this.tileItem15.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem15.CurrentFrameIndex = 1;
            tileItemElement45.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement45.Appearance.Hovered.Options.UseFont = true;
            tileItemElement45.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement45.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement45.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement45.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement45.Appearance.Normal.Options.UseFont = true;
            tileItemElement45.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement45.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement45.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement45.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement45.Appearance.Selected.Options.UseFont = true;
            tileItemElement45.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement45.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement45.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement45.Text = "Cơ hội";
            tileItemElement45.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement45.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement46.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement46.Appearance.Hovered.Options.UseFont = true;
            tileItemElement46.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement46.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement46.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement46.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement46.Appearance.Normal.Options.UseFont = true;
            tileItemElement46.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement46.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement46.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement46.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement46.Appearance.Selected.Options.UseFont = true;
            tileItemElement46.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement46.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement46.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement46.Text = "Quản lý khách hàng tiềm năng, cơ hội";
            tileItemElement46.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement46.TextLocation = new System.Drawing.Point(4, 27);
            this.tileItem15.Elements.Add(tileItemElement45);
            this.tileItem15.Elements.Add(tileItemElement46);
            tileItemFrame11.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement47.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image17")));
            tileItemElement47.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement47.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement47.ImageOptions.ImageSize = new System.Drawing.Size(50, 50);
            tileItemElement48.Text = "Cơ hội khách hàng";
            tileItemElement48.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileItemFrame11.Elements.Add(tileItemElement47);
            tileItemFrame11.Elements.Add(tileItemElement48);
            tileItemFrame11.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame11.Image")));
            tileItemFrame12.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement49.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement49.Appearance.Hovered.Options.UseFont = true;
            tileItemElement49.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement49.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement49.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement49.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement49.Appearance.Normal.Options.UseFont = true;
            tileItemElement49.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement49.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement49.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement49.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement49.Appearance.Selected.Options.UseFont = true;
            tileItemElement49.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement49.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement49.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement49.Text = "Cơ hội";
            tileItemElement49.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement49.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement50.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement50.Appearance.Hovered.Options.UseFont = true;
            tileItemElement50.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement50.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement50.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement50.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement50.Appearance.Normal.Options.UseFont = true;
            tileItemElement50.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement50.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement50.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement50.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement50.Appearance.Selected.Options.UseFont = true;
            tileItemElement50.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement50.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement50.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement50.Text = "Quản lý khách hàng tiềm năng, cơ hội";
            tileItemElement50.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement50.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame12.Elements.Add(tileItemElement49);
            tileItemFrame12.Elements.Add(tileItemElement50);
            this.tileItem15.Frames.Add(tileItemFrame11);
            this.tileItem15.Frames.Add(tileItemFrame12);
            this.tileItem15.Id = 36;
            this.tileItem15.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem15.Name = "tileItem15";
            // 
            // tileItem10
            // 
            this.tileItem10.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(159)))), ((int)(((byte)(0)))));
            this.tileItem10.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement51.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image18")));
            tileItemElement51.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement51.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            this.tileItem10.Elements.Add(tileItemElement51);
            this.tileItem10.Id = 33;
            this.tileItem10.ItemSize = DevExpress.XtraEditors.TileItemSize.Small;
            this.tileItem10.Name = "tileItem10";
            // 
            // tileItem11
            // 
            this.tileItem11.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(130)))), ((int)(((byte)(237)))));
            this.tileItem11.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement52.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image19")));
            tileItemElement52.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement52.Text = "";
            this.tileItem11.Elements.Add(tileItemElement52);
            this.tileItem11.Id = 34;
            this.tileItem11.ItemSize = DevExpress.XtraEditors.TileItemSize.Small;
            this.tileItem11.Name = "tileItem11";
            // 
            // CtlTotal
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.tileControl1);
            this.Name = "CtlTotal";
            this.Size = new System.Drawing.Size(667, 435);
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.XtraEditors.TileControl tileControl1;
        private DevExpress.XtraEditors.TileGroup tileGroup2;
        private DevExpress.XtraEditors.TileItem tileItem13;
        private DevExpress.XtraEditors.TileItem tileItem1;
        private DevExpress.XtraEditors.TileItem tileItem2;
        private DevExpress.XtraEditors.TileItem tileItem4;
        private DevExpress.XtraEditors.TileGroup tileGroup3;
        private DevExpress.XtraEditors.TileItem tileItem5;
        private DevExpress.XtraEditors.TileItem tileItem3;
        private DevExpress.XtraEditors.TileItem tileItem12;
        private DevExpress.XtraEditors.TileGroup tileGroup4;
        private DevExpress.XtraEditors.TileItem tileItem6;
        private DevExpress.XtraEditors.TileItem tileItem9;
        private DevExpress.XtraEditors.TileItem tileItem7;
        private DevExpress.XtraEditors.TileItem tileItem8;
        private DevExpress.XtraEditors.TileItem tileItem15;
        private DevExpress.XtraEditors.TileItem tileItem10;
        private DevExpress.XtraEditors.TileItem tileItem11;
    }
}
