namespace Building.Help
{
    partial class FrmManager
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DevExpress.XtraEditors.TileItemElement tileItemElement103 = new DevExpress.XtraEditors.TileItemElement();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmManager));
            DevExpress.XtraEditors.TileItemElement tileItemElement104 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame25 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement105 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement106 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame26 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement107 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement108 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame27 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement109 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement110 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame28 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement111 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement112 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement113 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement114 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement115 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement116 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement117 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement118 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement119 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement120 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement121 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement122 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement123 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame29 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement124 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement125 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame30 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement126 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement127 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement128 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement129 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame31 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement130 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame32 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement131 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement132 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement133 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement134 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame33 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement135 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame34 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement136 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement137 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement138 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement139 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement140 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement141 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement142 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement143 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement144 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement145 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement146 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement147 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement148 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame35 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement149 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement150 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame36 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement151 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement152 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement153 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement154 = new DevExpress.XtraEditors.TileItemElement();
            this.tileGroup3 = new DevExpress.XtraEditors.TileGroup();
            this.tileItem5 = new DevExpress.XtraEditors.TileItem();
            this.tileItem3 = new DevExpress.XtraEditors.TileItem();
            this.tileItem12 = new DevExpress.XtraEditors.TileItem();
            this.tileItem4 = new DevExpress.XtraEditors.TileItem();
            this.tileGroup2 = new DevExpress.XtraEditors.TileGroup();
            this.tileItem13 = new DevExpress.XtraEditors.TileItem();
            this.tileItem1 = new DevExpress.XtraEditors.TileItem();
            this.tileItem2 = new DevExpress.XtraEditors.TileItem();
            this.tileControl1 = new DevExpress.XtraEditors.TileControl();
            this.tileGroup4 = new DevExpress.XtraEditors.TileGroup();
            this.tileItem6 = new DevExpress.XtraEditors.TileItem();
            this.tileItem9 = new DevExpress.XtraEditors.TileItem();
            this.tileItem7 = new DevExpress.XtraEditors.TileItem();
            this.tileItem8 = new DevExpress.XtraEditors.TileItem();
            this.tileItem15 = new DevExpress.XtraEditors.TileItem();
            this.tileItem10 = new DevExpress.XtraEditors.TileItem();
            this.tileItem11 = new DevExpress.XtraEditors.TileItem();
            this.SuspendLayout();
            // 
            // tileGroup3
            // 
            this.tileGroup3.Items.Add(this.tileItem5);
            this.tileGroup3.Items.Add(this.tileItem3);
            this.tileGroup3.Items.Add(this.tileItem12);
            this.tileGroup3.Name = "tileGroup3";
            this.tileGroup3.Text = "Dự án";
            // 
            // tileItem5
            // 
            this.tileItem5.CurrentFrameIndex = 2;
            tileItemElement103.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image")));
            tileItemElement103.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement103.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement103.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement104.AnchorIndent = 25;
            tileItemElement104.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement104.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement104.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement104.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement104.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement104.Height = 20;
            tileItemElement104.StretchHorizontal = true;
            tileItemElement104.Text = "Quản lý mặt bằng";
            tileItemElement104.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            this.tileItem5.Elements.Add(tileItemElement103);
            this.tileItem5.Elements.Add(tileItemElement104);
            tileItemFrame25.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement105.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image1")));
            tileItemElement105.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement105.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement105.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement105.Text = "";
            tileItemElement106.AnchorIndent = 25;
            tileItemElement106.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement106.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement106.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement106.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement106.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement106.Height = 20;
            tileItemElement106.StretchHorizontal = true;
            tileItemElement106.Text = "Quản lý căn hộ";
            tileItemElement106.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemFrame25.Elements.Add(tileItemElement105);
            tileItemFrame25.Elements.Add(tileItemElement106);
            tileItemFrame25.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame25.Image")));
            tileItemFrame26.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement107.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image2")));
            tileItemElement107.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement107.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement107.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement107.Text = "";
            tileItemElement108.AnchorAlignment = DevExpress.Utils.AnchorAlignment.Left;
            tileItemElement108.AnchorIndent = 25;
            tileItemElement108.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement108.AnimateTransition = DevExpress.Utils.DefaultBoolean.True;
            tileItemElement108.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement108.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement108.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement108.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement108.Height = 20;
            tileItemElement108.StretchHorizontal = true;
            tileItemElement108.Text = "Quản lý mặt bằng";
            tileItemElement108.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement108.UseImageInTransition = false;
            tileItemFrame26.Elements.Add(tileItemElement107);
            tileItemFrame26.Elements.Add(tileItemElement108);
            tileItemFrame26.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame26.Image")));
            tileItemFrame27.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement109.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image3")));
            tileItemElement109.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement109.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement109.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement110.AnchorIndent = 25;
            tileItemElement110.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement110.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement110.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement110.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement110.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement110.Height = 20;
            tileItemElement110.StretchHorizontal = true;
            tileItemElement110.Text = "Quản lý mặt bằng";
            tileItemElement110.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemFrame27.Elements.Add(tileItemElement109);
            tileItemFrame27.Elements.Add(tileItemElement110);
            tileItemFrame27.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame27.Image")));
            tileItemFrame28.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement111.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image4")));
            tileItemElement111.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement111.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement111.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement112.AnchorIndent = 25;
            tileItemElement112.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement112.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement112.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement112.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement112.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement112.Height = 20;
            tileItemElement112.StretchHorizontal = true;
            tileItemElement112.Text = "Quản lý mặt bằng";
            tileItemElement112.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemFrame28.Elements.Add(tileItemElement111);
            tileItemFrame28.Elements.Add(tileItemElement112);
            tileItemFrame28.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame28.Image")));
            this.tileItem5.Frames.Add(tileItemFrame25);
            this.tileItem5.Frames.Add(tileItemFrame26);
            this.tileItem5.Frames.Add(tileItemFrame27);
            this.tileItem5.Frames.Add(tileItemFrame28);
            this.tileItem5.Id = 7;
            this.tileItem5.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem5.Name = "tileItem5";
            // 
            // tileItem3
            // 
            this.tileItem3.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.tileItem3.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement113.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement113.Appearance.Hovered.Options.UseFont = true;
            tileItemElement113.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement113.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement113.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement113.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement113.Appearance.Normal.Options.UseFont = true;
            tileItemElement113.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement113.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement113.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement113.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement113.Appearance.Selected.Options.UseFont = true;
            tileItemElement113.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement113.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement113.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement113.MaxWidth = 160;
            tileItemElement113.Text = "Phân quyền";
            tileItemElement113.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement113.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement114.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement114.Appearance.Hovered.Options.UseFont = true;
            tileItemElement114.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement114.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement114.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement114.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement114.Appearance.Normal.Options.UseFont = true;
            tileItemElement114.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement114.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement114.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement114.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement114.Appearance.Selected.Options.UseFont = true;
            tileItemElement114.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement114.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement114.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement114.MaxWidth = 160;
            tileItemElement114.Text = "Cài đặt phân quyền nhân viên, biểu đồ main";
            tileItemElement114.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement114.TextLocation = new System.Drawing.Point(75, 27);
            tileItemElement115.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image5")));
            tileItemElement115.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement115.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement115.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement115.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            this.tileItem3.Elements.Add(tileItemElement113);
            this.tileItem3.Elements.Add(tileItemElement114);
            this.tileItem3.Elements.Add(tileItemElement115);
            this.tileItem3.Id = 20;
            this.tileItem3.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem3.Name = "tileItem3";
            // 
            // tileItem12
            // 
            this.tileItem12.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(181)))), ((int)(((byte)(29)))), ((int)(((byte)(67)))));
            this.tileItem12.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement116.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement116.Appearance.Hovered.Options.UseFont = true;
            tileItemElement116.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement116.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement116.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement116.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement116.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement116.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement116.Appearance.Normal.Options.UseFont = true;
            tileItemElement116.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement116.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement116.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement116.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement116.Appearance.Selected.Options.UseFont = true;
            tileItemElement116.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement116.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement116.Height = 20;
            tileItemElement116.StretchHorizontal = true;
            tileItemElement116.Text = "Kinh phí dự trù";
            tileItemElement116.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement116.TextLocation = new System.Drawing.Point(3, 75);
            tileItemElement117.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image6")));
            tileItemElement117.ImageOptions.ImageLocation = new System.Drawing.Point(90, -40);
            tileItemElement117.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement117.ImageOptions.ImageSize = new System.Drawing.Size(50, 50);
            this.tileItem12.Elements.Add(tileItemElement116);
            this.tileItem12.Elements.Add(tileItemElement117);
            this.tileItem12.Id = 29;
            this.tileItem12.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem12.Name = "tileItem12";
            // 
            // tileItem4
            // 
            this.tileItem4.AppearanceItem.Normal.BackColor = System.Drawing.SystemColors.MenuHighlight;
            this.tileItem4.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement118.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement118.Appearance.Hovered.Options.UseFont = true;
            tileItemElement118.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement118.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement118.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement118.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement118.Appearance.Normal.Options.UseFont = true;
            tileItemElement118.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement118.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement118.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement118.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement118.Appearance.Selected.Options.UseFont = true;
            tileItemElement118.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement118.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement118.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement118.MaxWidth = 170;
            tileItemElement118.Text = "Dự án";
            tileItemElement118.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement118.TextLocation = new System.Drawing.Point(3, 0);
            tileItemElement119.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement119.Appearance.Hovered.Options.UseFont = true;
            tileItemElement119.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement119.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement119.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement119.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement119.Appearance.Normal.Options.UseFont = true;
            tileItemElement119.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement119.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement119.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement119.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement119.Appearance.Selected.Options.UseFont = true;
            tileItemElement119.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement119.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement119.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement119.MaxWidth = 160;
            tileItemElement119.Text = "Khai báo, cài đặt các căn hộ, kinh phí dự trù";
            tileItemElement119.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement119.TextLocation = new System.Drawing.Point(3, 27);
            tileItemElement120.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image7")));
            tileItemElement120.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement120.ImageOptions.ImageLocation = new System.Drawing.Point(172, 8);
            tileItemElement120.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement120.ImageOptions.ImageSize = new System.Drawing.Size(48, 48);
            tileItemElement121.AnchorElementIndex = 1;
            tileItemElement121.AnchorIndent = 25;
            tileItemElement121.AnchorOffset = new System.Drawing.Point(40, 0);
            tileItemElement121.Appearance.Normal.BackColor = System.Drawing.Color.Azure;
            tileItemElement121.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            tileItemElement121.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement121.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement121.Height = 20;
            tileItemElement121.StretchHorizontal = true;
            tileItemElement121.Text = "Thông tin dự án";
            this.tileItem4.Elements.Add(tileItemElement118);
            this.tileItem4.Elements.Add(tileItemElement119);
            this.tileItem4.Elements.Add(tileItemElement120);
            this.tileItem4.Elements.Add(tileItemElement121);
            this.tileItem4.Id = 6;
            this.tileItem4.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem4.Name = "tileItem4";
            // 
            // tileGroup2
            // 
            this.tileGroup2.Items.Add(this.tileItem13);
            this.tileGroup2.Items.Add(this.tileItem1);
            this.tileGroup2.Items.Add(this.tileItem2);
            this.tileGroup2.Items.Add(this.tileItem4);
            this.tileGroup2.Name = "tileGroup2";
            this.tileGroup2.Text = "Hệ thống";
            // 
            // tileItem13
            // 
            this.tileItem13.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(144)))), ((int)(((byte)(163)))));
            this.tileItem13.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem13.CurrentFrameIndex = 1;
            tileItemElement122.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image8")));
            tileItemElement122.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement122.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement122.ImageOptions.ImageSize = new System.Drawing.Size(270, 150);
            tileItemElement123.Text = "Hướng dẫn sử dụng";
            tileItemElement123.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItem13.Elements.Add(tileItemElement122);
            this.tileItem13.Elements.Add(tileItemElement123);
            tileItemFrame29.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement124.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image9")));
            tileItemElement124.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement124.ImageOptions.ImageLocation = new System.Drawing.Point(70, 60);
            tileItemElement124.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement124.ImageOptions.ImageSize = new System.Drawing.Size(100, 100);
            tileItemElement125.Text = "Hướng dẫn sử dụng";
            tileItemElement125.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileItemFrame29.Elements.Add(tileItemElement124);
            tileItemFrame29.Elements.Add(tileItemElement125);
            tileItemFrame29.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame29.Image")));
            tileItemFrame30.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemElement126.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image10")));
            tileItemElement126.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement126.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement126.ImageOptions.ImageSize = new System.Drawing.Size(270, 150);
            tileItemElement127.Text = "Hướng dẫn sử dụng";
            tileItemElement127.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileItemFrame30.Elements.Add(tileItemElement126);
            tileItemFrame30.Elements.Add(tileItemElement127);
            tileItemFrame30.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame30.Image")));
            this.tileItem13.Frames.Add(tileItemFrame29);
            this.tileItem13.Frames.Add(tileItemFrame30);
            this.tileItem13.Id = 30;
            this.tileItem13.ItemSize = DevExpress.XtraEditors.TileItemSize.Large;
            this.tileItem13.Name = "tileItem13";
            // 
            // tileItem1
            // 
            this.tileItem1.AppearanceItem.Normal.BackColor = System.Drawing.SystemColors.Highlight;
            this.tileItem1.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem1.CurrentFrameIndex = 1;
            tileItemElement128.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement128.Appearance.Hovered.Options.UseFont = true;
            tileItemElement128.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement128.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement128.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement128.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement128.Appearance.Normal.Options.UseFont = true;
            tileItemElement128.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement128.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement128.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement128.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement128.Appearance.Selected.Options.UseFont = true;
            tileItemElement128.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement128.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement128.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement128.Text = "System";
            tileItemElement128.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement128.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement129.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement129.Appearance.Hovered.Options.UseFont = true;
            tileItemElement129.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement129.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement129.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement129.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement129.Appearance.Normal.Options.UseFont = true;
            tileItemElement129.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement129.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement129.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement129.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement129.Appearance.Selected.Options.UseFont = true;
            tileItemElement129.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement129.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement129.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement129.Text = "Cấu hình hệ thống, ngôn ngữ, FTP, giao diện";
            tileItemElement129.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement129.TextLocation = new System.Drawing.Point(4, 27);
            this.tileItem1.Elements.Add(tileItemElement128);
            this.tileItem1.Elements.Add(tileItemElement129);
            tileItemFrame31.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement130.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image11")));
            tileItemElement130.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement130.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement130.ImageOptions.ImageSize = new System.Drawing.Size(50, 50);
            tileItemFrame31.Elements.Add(tileItemElement130);
            tileItemFrame31.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame31.Image")));
            tileItemFrame32.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement131.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement131.Appearance.Hovered.Options.UseFont = true;
            tileItemElement131.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement131.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement131.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement131.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement131.Appearance.Normal.Options.UseFont = true;
            tileItemElement131.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement131.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement131.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement131.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement131.Appearance.Selected.Options.UseFont = true;
            tileItemElement131.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement131.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement131.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement131.Text = "System";
            tileItemElement131.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement131.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement132.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement132.Appearance.Hovered.Options.UseFont = true;
            tileItemElement132.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement132.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement132.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement132.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement132.Appearance.Normal.Options.UseFont = true;
            tileItemElement132.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement132.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement132.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement132.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement132.Appearance.Selected.Options.UseFont = true;
            tileItemElement132.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement132.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement132.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement132.Text = "Cấu hình hệ thống, ngôn ngữ, FTP, giao diện";
            tileItemElement132.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement132.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame32.Elements.Add(tileItemElement131);
            tileItemFrame32.Elements.Add(tileItemElement132);
            this.tileItem1.Frames.Add(tileItemFrame31);
            this.tileItem1.Frames.Add(tileItemFrame32);
            this.tileItem1.Id = 14;
            this.tileItem1.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem1.Name = "tileItem1";
            // 
            // tileItem2
            // 
            this.tileItem2.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.tileItem2.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem2.CurrentFrameIndex = 1;
            tileItemElement133.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement133.Appearance.Hovered.Options.UseFont = true;
            tileItemElement133.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement133.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement133.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement133.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement133.Appearance.Normal.Options.UseFont = true;
            tileItemElement133.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement133.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement133.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement133.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement133.Appearance.Selected.Options.UseFont = true;
            tileItemElement133.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement133.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement133.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement133.Text = "Tài liệu";
            tileItemElement133.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement133.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement134.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement134.Appearance.Hovered.Options.UseFont = true;
            tileItemElement134.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement134.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement134.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement134.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement134.Appearance.Normal.Options.UseFont = true;
            tileItemElement134.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement134.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement134.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement134.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement134.Appearance.Selected.Options.UseFont = true;
            tileItemElement134.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement134.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement134.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement134.Text = "Cấu hình nhóm biểu mẫu, trường trộn, tài liệu, biểu mẫu ";
            tileItemElement134.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement134.TextLocation = new System.Drawing.Point(4, 27);
            this.tileItem2.Elements.Add(tileItemElement133);
            this.tileItem2.Elements.Add(tileItemElement134);
            tileItemFrame33.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement135.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image12")));
            tileItemElement135.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement135.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement135.ImageOptions.ImageSize = new System.Drawing.Size(50, 50);
            tileItemFrame33.Elements.Add(tileItemElement135);
            tileItemFrame33.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame33.Image")));
            tileItemFrame34.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement136.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement136.Appearance.Hovered.Options.UseFont = true;
            tileItemElement136.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement136.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement136.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement136.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement136.Appearance.Normal.Options.UseFont = true;
            tileItemElement136.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement136.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement136.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement136.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement136.Appearance.Selected.Options.UseFont = true;
            tileItemElement136.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement136.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement136.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement136.Text = "Tài liệu";
            tileItemElement136.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement136.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement137.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement137.Appearance.Hovered.Options.UseFont = true;
            tileItemElement137.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement137.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement137.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement137.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement137.Appearance.Normal.Options.UseFont = true;
            tileItemElement137.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement137.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement137.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement137.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement137.Appearance.Selected.Options.UseFont = true;
            tileItemElement137.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement137.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement137.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement137.Text = "Cấu hình nhóm biểu mẫu, trường trộn, tài liệu, biểu mẫu ";
            tileItemElement137.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement137.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame34.Elements.Add(tileItemElement136);
            tileItemFrame34.Elements.Add(tileItemElement137);
            this.tileItem2.Frames.Add(tileItemFrame33);
            this.tileItem2.Frames.Add(tileItemFrame34);
            this.tileItem2.Id = 19;
            this.tileItem2.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem2.Name = "tileItem2";
            // 
            // tileControl1
            // 
            this.tileControl1.AllowDrag = false;
            this.tileControl1.AllowDragTilesBetweenGroups = false;
            this.tileControl1.AllowItemHover = true;
            this.tileControl1.AppearanceGroupText.ForeColor = System.Drawing.Color.White;
            this.tileControl1.AppearanceGroupText.Options.UseForeColor = true;
            this.tileControl1.AppearanceItem.Normal.ForeColor = System.Drawing.Color.White;
            this.tileControl1.AppearanceItem.Normal.Options.UseForeColor = true;
            this.tileControl1.AppearanceText.ForeColor = System.Drawing.Color.White;
            this.tileControl1.AppearanceText.Options.UseForeColor = true;
            this.tileControl1.AppearanceText.Options.UseTextOptions = true;
            this.tileControl1.AppearanceText.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.tileControl1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(130)))), ((int)(((byte)(248)))));
            this.tileControl1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tileControl1.BackgroundImage")));
            this.tileControl1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tileControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tileControl1.Groups.Add(this.tileGroup2);
            this.tileControl1.Groups.Add(this.tileGroup3);
            this.tileControl1.Groups.Add(this.tileGroup4);
            this.tileControl1.ItemBorderVisibility = DevExpress.XtraEditors.TileItemBorderVisibility.Never;
            this.tileControl1.Location = new System.Drawing.Point(0, 0);
            this.tileControl1.MaxId = 37;
            this.tileControl1.Name = "tileControl1";
            this.tileControl1.ShowGroupText = true;
            this.tileControl1.ShowText = true;
            this.tileControl1.Size = new System.Drawing.Size(795, 625);
            this.tileControl1.TabIndex = 0;
            this.tileControl1.Text = "Hướng dẫn sử dụng Phần mềm Building";
            this.tileControl1.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileControl1_ItemClick);
            // 
            // tileGroup4
            // 
            this.tileGroup4.Items.Add(this.tileItem6);
            this.tileGroup4.Items.Add(this.tileItem9);
            this.tileGroup4.Items.Add(this.tileItem7);
            this.tileGroup4.Items.Add(this.tileItem8);
            this.tileGroup4.Items.Add(this.tileItem15);
            this.tileGroup4.Items.Add(this.tileItem10);
            this.tileGroup4.Items.Add(this.tileItem11);
            this.tileGroup4.Name = "tileGroup4";
            this.tileGroup4.Text = "Khách hàng";
            // 
            // tileItem6
            // 
            this.tileItem6.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(61)))), ((int)(((byte)(186)))));
            this.tileItem6.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement138.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image13")));
            tileItemElement138.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement138.ImageOptions.ImageLocation = new System.Drawing.Point(60, 60);
            tileItemElement138.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement138.ImageOptions.ImageSize = new System.Drawing.Size(100, 100);
            tileItemElement138.ImageOptions.ImageToTextAlignment = DevExpress.XtraEditors.TileControlImageToTextAlignment.None;
            tileItemElement138.Text = "Khách hàng";
            tileItemElement138.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItem6.Elements.Add(tileItemElement138);
            this.tileItem6.Id = 8;
            this.tileItem6.ItemSize = DevExpress.XtraEditors.TileItemSize.Large;
            this.tileItem6.Name = "tileItem6";
            // 
            // tileItem9
            // 
            this.tileItem9.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(81)))), ((int)(((byte)(43)))));
            this.tileItem9.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement139.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement139.Appearance.Hovered.Options.UseFont = true;
            tileItemElement139.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement139.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement139.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement139.Appearance.Normal.Options.UseFont = true;
            tileItemElement139.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement139.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement139.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement139.Appearance.Selected.Options.UseFont = true;
            tileItemElement139.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement139.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement139.Text = "Quản lý cư dân";
            tileItemElement139.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement139.TextLocation = new System.Drawing.Point(3, 75);
            tileItemElement140.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image14")));
            tileItemElement140.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement140.ImageOptions.ImageLocation = new System.Drawing.Point(-12, -8);
            tileItemElement140.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            tileItemElement140.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            this.tileItem9.Elements.Add(tileItemElement139);
            this.tileItem9.Elements.Add(tileItemElement140);
            this.tileItem9.Id = 25;
            this.tileItem9.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem9.Name = "tileItem9";
            // 
            // tileItem7
            // 
            this.tileItem7.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(134)))), ((int)(((byte)(153)))));
            this.tileItem7.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement141.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement141.Appearance.Hovered.Options.UseFont = true;
            tileItemElement141.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement141.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement141.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement141.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement141.Appearance.Normal.Options.UseFont = true;
            tileItemElement141.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement141.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement141.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement141.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement141.Appearance.Selected.Options.UseFont = true;
            tileItemElement141.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement141.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement141.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement141.MaxWidth = 160;
            tileItemElement141.Text = "Yêu cầu";
            tileItemElement141.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement141.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement142.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement142.Appearance.Hovered.Options.UseFont = true;
            tileItemElement142.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement142.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement142.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement142.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement142.Appearance.Normal.Options.UseFont = true;
            tileItemElement142.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement142.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement142.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement142.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement142.Appearance.Selected.Options.UseFont = true;
            tileItemElement142.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement142.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement142.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement142.MaxWidth = 160;
            tileItemElement142.Text = "Quản lý các yêu cầu, phản hồi từ cư dân";
            tileItemElement142.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement142.TextLocation = new System.Drawing.Point(75, 27);
            tileItemElement143.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image15")));
            tileItemElement143.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement143.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement143.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement143.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            this.tileItem7.Elements.Add(tileItemElement141);
            this.tileItem7.Elements.Add(tileItemElement142);
            this.tileItem7.Elements.Add(tileItemElement143);
            this.tileItem7.Id = 31;
            this.tileItem7.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem7.Name = "tileItem7";
            // 
            // tileItem8
            // 
            this.tileItem8.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(181)))), ((int)(((byte)(29)))), ((int)(((byte)(67)))));
            this.tileItem8.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement144.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement144.Appearance.Hovered.Options.UseFont = true;
            tileItemElement144.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement144.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement144.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement144.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement144.Appearance.Normal.Options.UseFont = true;
            tileItemElement144.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement144.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement144.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement144.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement144.Appearance.Selected.Options.UseFont = true;
            tileItemElement144.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement144.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement144.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement144.MaxWidth = 170;
            tileItemElement144.Text = "Lễ tân";
            tileItemElement144.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement144.TextLocation = new System.Drawing.Point(3, 0);
            tileItemElement145.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement145.Appearance.Hovered.Options.UseFont = true;
            tileItemElement145.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement145.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement145.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement145.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement145.Appearance.Normal.Options.UseFont = true;
            tileItemElement145.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement145.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement145.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement145.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement145.Appearance.Selected.Options.UseFont = true;
            tileItemElement145.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement145.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement145.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement145.MaxWidth = 160;
            tileItemElement145.Text = "Quản lý lễ tân, khách hàng vào ra, thời gian, địa điểm";
            tileItemElement145.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement145.TextLocation = new System.Drawing.Point(3, 27);
            tileItemElement146.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image16")));
            tileItemElement146.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement146.ImageOptions.ImageLocation = new System.Drawing.Point(172, 8);
            tileItemElement146.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement146.ImageOptions.ImageSize = new System.Drawing.Size(48, 64);
            this.tileItem8.Elements.Add(tileItemElement144);
            this.tileItem8.Elements.Add(tileItemElement145);
            this.tileItem8.Elements.Add(tileItemElement146);
            this.tileItem8.Id = 32;
            this.tileItem8.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem8.Name = "tileItem8";
            // 
            // tileItem15
            // 
            this.tileItem15.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(85)))), ((int)(((byte)(189)))));
            this.tileItem15.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem15.CurrentFrameIndex = 1;
            tileItemElement147.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement147.Appearance.Hovered.Options.UseFont = true;
            tileItemElement147.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement147.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement147.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement147.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement147.Appearance.Normal.Options.UseFont = true;
            tileItemElement147.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement147.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement147.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement147.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement147.Appearance.Selected.Options.UseFont = true;
            tileItemElement147.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement147.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement147.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement147.Text = "Cơ hội";
            tileItemElement147.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement147.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement148.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement148.Appearance.Hovered.Options.UseFont = true;
            tileItemElement148.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement148.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement148.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement148.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement148.Appearance.Normal.Options.UseFont = true;
            tileItemElement148.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement148.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement148.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement148.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement148.Appearance.Selected.Options.UseFont = true;
            tileItemElement148.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement148.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement148.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement148.Text = "Quản lý khách hàng tiềm năng, cơ hội";
            tileItemElement148.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement148.TextLocation = new System.Drawing.Point(4, 27);
            this.tileItem15.Elements.Add(tileItemElement147);
            this.tileItem15.Elements.Add(tileItemElement148);
            tileItemFrame35.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement149.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image17")));
            tileItemElement149.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement149.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement149.ImageOptions.ImageSize = new System.Drawing.Size(50, 50);
            tileItemElement150.Text = "Cơ hội khách hàng";
            tileItemElement150.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileItemFrame35.Elements.Add(tileItemElement149);
            tileItemFrame35.Elements.Add(tileItemElement150);
            tileItemFrame35.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame35.Image")));
            tileItemFrame36.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement151.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement151.Appearance.Hovered.Options.UseFont = true;
            tileItemElement151.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement151.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement151.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement151.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement151.Appearance.Normal.Options.UseFont = true;
            tileItemElement151.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement151.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement151.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement151.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement151.Appearance.Selected.Options.UseFont = true;
            tileItemElement151.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement151.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement151.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement151.Text = "Cơ hội";
            tileItemElement151.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement151.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement152.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement152.Appearance.Hovered.Options.UseFont = true;
            tileItemElement152.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement152.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement152.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement152.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement152.Appearance.Normal.Options.UseFont = true;
            tileItemElement152.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement152.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement152.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement152.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement152.Appearance.Selected.Options.UseFont = true;
            tileItemElement152.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement152.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement152.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement152.Text = "Quản lý khách hàng tiềm năng, cơ hội";
            tileItemElement152.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement152.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame36.Elements.Add(tileItemElement151);
            tileItemFrame36.Elements.Add(tileItemElement152);
            this.tileItem15.Frames.Add(tileItemFrame35);
            this.tileItem15.Frames.Add(tileItemFrame36);
            this.tileItem15.Id = 36;
            this.tileItem15.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem15.Name = "tileItem15";
            // 
            // tileItem10
            // 
            this.tileItem10.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(159)))), ((int)(((byte)(0)))));
            this.tileItem10.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement153.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image18")));
            tileItemElement153.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement153.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            this.tileItem10.Elements.Add(tileItemElement153);
            this.tileItem10.Id = 33;
            this.tileItem10.ItemSize = DevExpress.XtraEditors.TileItemSize.Small;
            this.tileItem10.Name = "tileItem10";
            // 
            // tileItem11
            // 
            this.tileItem11.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(130)))), ((int)(((byte)(237)))));
            this.tileItem11.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement154.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image19")));
            tileItemElement154.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement154.Text = "";
            this.tileItem11.Elements.Add(tileItemElement154);
            this.tileItem11.Id = 34;
            this.tileItem11.ItemSize = DevExpress.XtraEditors.TileItemSize.Small;
            this.tileItem11.Name = "tileItem11";
            // 
            // FrmManager
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(795, 625);
            this.Controls.Add(this.tileControl1);
            this.Name = "FrmManager";
            this.Text = "Hướng dẫn sử dụng";
            this.Load += new System.EventHandler(this.FrmManager_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.XtraEditors.TileGroup tileGroup3;
        private DevExpress.XtraEditors.TileItem tileItem4;
        private DevExpress.XtraEditors.TileItem tileItem5;
        private DevExpress.XtraEditors.TileGroup tileGroup2;
        private DevExpress.XtraEditors.TileControl tileControl1;
        private DevExpress.XtraEditors.TileGroup tileGroup4;
        private DevExpress.XtraEditors.TileItem tileItem6;
        private DevExpress.XtraEditors.TileItem tileItem1;
        private DevExpress.XtraEditors.TileItem tileItem2;
        private DevExpress.XtraEditors.TileItem tileItem3;
        private DevExpress.XtraEditors.TileItem tileItem9;
        private DevExpress.XtraEditors.TileItem tileItem12;
        private DevExpress.XtraEditors.TileItem tileItem13;
        private DevExpress.XtraEditors.TileItem tileItem7;
        private DevExpress.XtraEditors.TileItem tileItem8;
        private DevExpress.XtraEditors.TileItem tileItem10;
        private DevExpress.XtraEditors.TileItem tileItem11;
        private DevExpress.XtraEditors.TileItem tileItem15;
    }
}