#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="building_db")]
	public partial class MasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttnKhachHang(tnKhachHang instance);
    partial void UpdatetnKhachHang(tnKhachHang instance);
    partial void DeletetnKhachHang(tnKhachHang instance);
    partial void InsertSendMailNhacNo(SendMailNhacNo instance);
    partial void UpdateSendMailNhacNo(SendMailNhacNo instance);
    partial void DeleteSendMailNhacNo(SendMailNhacNo instance);
    partial void InsertSendMailDetail(SendMailDetail instance);
    partial void UpdateSendMailDetail(SendMailDetail instance);
    partial void DeleteSendMailDetail(SendMailDetail instance);
    partial void InsertSendMailAccount(SendMailAccount instance);
    partial void UpdateSendMailAccount(SendMailAccount instance);
    partial void DeleteSendMailAccount(SendMailAccount instance);
    partial void InsertSendMail(SendMail instance);
    partial void UpdateSendMail(SendMail instance);
    partial void DeleteSendMail(SendMail instance);
    #endregion
		
		public MasterDataContext() : 
				base(global::BuildingService.Properties.Settings.Default.building_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tnKhachHang> tnKhachHangs
		{
			get
			{
				return this.GetTable<tnKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<SendMailNhacNo> SendMailNhacNos
		{
			get
			{
				return this.GetTable<SendMailNhacNo>();
			}
		}
		
		public System.Data.Linq.Table<SendMailDetail> SendMailDetails
		{
			get
			{
				return this.GetTable<SendMailDetail>();
			}
		}
		
		public System.Data.Linq.Table<SendMailAccount> SendMailAccounts
		{
			get
			{
				return this.GetTable<SendMailAccount>();
			}
		}
		
		public System.Data.Linq.Table<SendMail> SendMails
		{
			get
			{
				return this.GetTable<SendMail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnKhachHang")]
	public partial class tnKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _HoKH;
		
		private string _TenKH;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DienThoaiKH;
		
		private string _EmailKH;
		
		private string _DCTT;
		
		private string _DCLL;
		
		private string _CMND;
		
		private string _NgayCap;
		
		private string _NoiCap;
		
		private System.Nullable<bool> _IsCaNhan;
		
		private string _CtyTen;
		
		private string _CtyTenVT;
		
		private string _CtyDiaChi;
		
		private string _CtyFax;
		
		private string _CtyDienThoai;
		
		private string _CtySoDKKD;
		
		private string _CtyNgayDKKD;
		
		private string _CtyNoiDKKD;
		
		private string _CtyNguoiDD;
		
		private string _CtyChucVuDD;
		
		private string _CtySoTKNH;
		
		private string _CtyTenNH;
		
		private string _CtyMaSoThue;
		
		private System.Nullable<int> _MaKV;
		
		private System.Nullable<int> _MaNV;
		
		private System.Nullable<byte> _MaTN;
		
		private EntitySet<SendMailNhacNo> _SendMailNhacNos;
		
		private EntitySet<SendMailDetail> _SendMailDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnHoKHChanging(string value);
    partial void OnHoKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDienThoaiKHChanging(string value);
    partial void OnDienThoaiKHChanged();
    partial void OnEmailKHChanging(string value);
    partial void OnEmailKHChanged();
    partial void OnDCTTChanging(string value);
    partial void OnDCTTChanged();
    partial void OnDCLLChanging(string value);
    partial void OnDCLLChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnNgayCapChanging(string value);
    partial void OnNgayCapChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    partial void OnIsCaNhanChanging(System.Nullable<bool> value);
    partial void OnIsCaNhanChanged();
    partial void OnCtyTenChanging(string value);
    partial void OnCtyTenChanged();
    partial void OnCtyTenVTChanging(string value);
    partial void OnCtyTenVTChanged();
    partial void OnCtyDiaChiChanging(string value);
    partial void OnCtyDiaChiChanged();
    partial void OnCtyFaxChanging(string value);
    partial void OnCtyFaxChanged();
    partial void OnCtyDienThoaiChanging(string value);
    partial void OnCtyDienThoaiChanged();
    partial void OnCtySoDKKDChanging(string value);
    partial void OnCtySoDKKDChanged();
    partial void OnCtyNgayDKKDChanging(string value);
    partial void OnCtyNgayDKKDChanged();
    partial void OnCtyNoiDKKDChanging(string value);
    partial void OnCtyNoiDKKDChanged();
    partial void OnCtyNguoiDDChanging(string value);
    partial void OnCtyNguoiDDChanged();
    partial void OnCtyChucVuDDChanging(string value);
    partial void OnCtyChucVuDDChanged();
    partial void OnCtySoTKNHChanging(string value);
    partial void OnCtySoTKNHChanged();
    partial void OnCtyTenNHChanging(string value);
    partial void OnCtyTenNHChanged();
    partial void OnCtyMaSoThueChanging(string value);
    partial void OnCtyMaSoThueChanged();
    partial void OnMaKVChanging(System.Nullable<int> value);
    partial void OnMaKVChanged();
    partial void OnMaNVChanging(System.Nullable<int> value);
    partial void OnMaNVChanged();
    partial void OnMaTNChanging(System.Nullable<byte> value);
    partial void OnMaTNChanged();
    #endregion
		
		public tnKhachHang()
		{
			this._SendMailNhacNos = new EntitySet<SendMailNhacNo>(new Action<SendMailNhacNo>(this.attach_SendMailNhacNos), new Action<SendMailNhacNo>(this.detach_SendMailNhacNos));
			this._SendMailDetails = new EntitySet<SendMailDetail>(new Action<SendMailDetail>(this.attach_SendMailDetails), new Action<SendMailDetail>(this.detach_SendMailDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoKH", DbType="NVarChar(50)")]
		public string HoKH
		{
			get
			{
				return this._HoKH;
			}
			set
			{
				if ((this._HoKH != value))
				{
					this.OnHoKHChanging(value);
					this.SendPropertyChanging();
					this._HoKH = value;
					this.SendPropertyChanged("HoKH");
					this.OnHoKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(10)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiKH", DbType="NVarChar(50)")]
		public string DienThoaiKH
		{
			get
			{
				return this._DienThoaiKH;
			}
			set
			{
				if ((this._DienThoaiKH != value))
				{
					this.OnDienThoaiKHChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiKH = value;
					this.SendPropertyChanged("DienThoaiKH");
					this.OnDienThoaiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailKH", DbType="NVarChar(50)")]
		public string EmailKH
		{
			get
			{
				return this._EmailKH;
			}
			set
			{
				if ((this._EmailKH != value))
				{
					this.OnEmailKHChanging(value);
					this.SendPropertyChanging();
					this._EmailKH = value;
					this.SendPropertyChanged("EmailKH");
					this.OnEmailKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCTT", DbType="NVarChar(150)")]
		public string DCTT
		{
			get
			{
				return this._DCTT;
			}
			set
			{
				if ((this._DCTT != value))
				{
					this.OnDCTTChanging(value);
					this.SendPropertyChanging();
					this._DCTT = value;
					this.SendPropertyChanged("DCTT");
					this.OnDCTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCLL", DbType="NVarChar(150)")]
		public string DCLL
		{
			get
			{
				return this._DCLL;
			}
			set
			{
				if ((this._DCLL != value))
				{
					this.OnDCLLChanging(value);
					this.SendPropertyChanging();
					this._DCLL = value;
					this.SendPropertyChanged("DCLL");
					this.OnDCLLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(20)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="NVarChar(10)")]
		public string NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NVarChar(50)")]
		public string NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCaNhan", DbType="Bit")]
		public System.Nullable<bool> IsCaNhan
		{
			get
			{
				return this._IsCaNhan;
			}
			set
			{
				if ((this._IsCaNhan != value))
				{
					this.OnIsCaNhanChanging(value);
					this.SendPropertyChanging();
					this._IsCaNhan = value;
					this.SendPropertyChanged("IsCaNhan");
					this.OnIsCaNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyTen", DbType="NVarChar(150)")]
		public string CtyTen
		{
			get
			{
				return this._CtyTen;
			}
			set
			{
				if ((this._CtyTen != value))
				{
					this.OnCtyTenChanging(value);
					this.SendPropertyChanging();
					this._CtyTen = value;
					this.SendPropertyChanged("CtyTen");
					this.OnCtyTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyTenVT", DbType="NVarChar(50)")]
		public string CtyTenVT
		{
			get
			{
				return this._CtyTenVT;
			}
			set
			{
				if ((this._CtyTenVT != value))
				{
					this.OnCtyTenVTChanging(value);
					this.SendPropertyChanging();
					this._CtyTenVT = value;
					this.SendPropertyChanged("CtyTenVT");
					this.OnCtyTenVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyDiaChi", DbType="NVarChar(150)")]
		public string CtyDiaChi
		{
			get
			{
				return this._CtyDiaChi;
			}
			set
			{
				if ((this._CtyDiaChi != value))
				{
					this.OnCtyDiaChiChanging(value);
					this.SendPropertyChanging();
					this._CtyDiaChi = value;
					this.SendPropertyChanged("CtyDiaChi");
					this.OnCtyDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyFax", DbType="NVarChar(50)")]
		public string CtyFax
		{
			get
			{
				return this._CtyFax;
			}
			set
			{
				if ((this._CtyFax != value))
				{
					this.OnCtyFaxChanging(value);
					this.SendPropertyChanging();
					this._CtyFax = value;
					this.SendPropertyChanged("CtyFax");
					this.OnCtyFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyDienThoai", DbType="NVarChar(50)")]
		public string CtyDienThoai
		{
			get
			{
				return this._CtyDienThoai;
			}
			set
			{
				if ((this._CtyDienThoai != value))
				{
					this.OnCtyDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._CtyDienThoai = value;
					this.SendPropertyChanged("CtyDienThoai");
					this.OnCtyDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtySoDKKD", DbType="NVarChar(50)")]
		public string CtySoDKKD
		{
			get
			{
				return this._CtySoDKKD;
			}
			set
			{
				if ((this._CtySoDKKD != value))
				{
					this.OnCtySoDKKDChanging(value);
					this.SendPropertyChanging();
					this._CtySoDKKD = value;
					this.SendPropertyChanged("CtySoDKKD");
					this.OnCtySoDKKDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyNgayDKKD", DbType="NVarChar(50)")]
		public string CtyNgayDKKD
		{
			get
			{
				return this._CtyNgayDKKD;
			}
			set
			{
				if ((this._CtyNgayDKKD != value))
				{
					this.OnCtyNgayDKKDChanging(value);
					this.SendPropertyChanging();
					this._CtyNgayDKKD = value;
					this.SendPropertyChanged("CtyNgayDKKD");
					this.OnCtyNgayDKKDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyNoiDKKD", DbType="NVarChar(50)")]
		public string CtyNoiDKKD
		{
			get
			{
				return this._CtyNoiDKKD;
			}
			set
			{
				if ((this._CtyNoiDKKD != value))
				{
					this.OnCtyNoiDKKDChanging(value);
					this.SendPropertyChanging();
					this._CtyNoiDKKD = value;
					this.SendPropertyChanged("CtyNoiDKKD");
					this.OnCtyNoiDKKDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyNguoiDD", DbType="NVarChar(50)")]
		public string CtyNguoiDD
		{
			get
			{
				return this._CtyNguoiDD;
			}
			set
			{
				if ((this._CtyNguoiDD != value))
				{
					this.OnCtyNguoiDDChanging(value);
					this.SendPropertyChanging();
					this._CtyNguoiDD = value;
					this.SendPropertyChanged("CtyNguoiDD");
					this.OnCtyNguoiDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyChucVuDD", DbType="NVarChar(50)")]
		public string CtyChucVuDD
		{
			get
			{
				return this._CtyChucVuDD;
			}
			set
			{
				if ((this._CtyChucVuDD != value))
				{
					this.OnCtyChucVuDDChanging(value);
					this.SendPropertyChanging();
					this._CtyChucVuDD = value;
					this.SendPropertyChanged("CtyChucVuDD");
					this.OnCtyChucVuDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtySoTKNH", DbType="NVarChar(50)")]
		public string CtySoTKNH
		{
			get
			{
				return this._CtySoTKNH;
			}
			set
			{
				if ((this._CtySoTKNH != value))
				{
					this.OnCtySoTKNHChanging(value);
					this.SendPropertyChanging();
					this._CtySoTKNH = value;
					this.SendPropertyChanged("CtySoTKNH");
					this.OnCtySoTKNHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyTenNH", DbType="NVarChar(150)")]
		public string CtyTenNH
		{
			get
			{
				return this._CtyTenNH;
			}
			set
			{
				if ((this._CtyTenNH != value))
				{
					this.OnCtyTenNHChanging(value);
					this.SendPropertyChanging();
					this._CtyTenNH = value;
					this.SendPropertyChanged("CtyTenNH");
					this.OnCtyTenNHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtyMaSoThue", DbType="NVarChar(50)")]
		public string CtyMaSoThue
		{
			get
			{
				return this._CtyMaSoThue;
			}
			set
			{
				if ((this._CtyMaSoThue != value))
				{
					this.OnCtyMaSoThueChanging(value);
					this.SendPropertyChanging();
					this._CtyMaSoThue = value;
					this.SendPropertyChanged("CtyMaSoThue");
					this.OnCtyMaSoThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKV", DbType="Int")]
		public System.Nullable<int> MaKV
		{
			get
			{
				return this._MaKV;
			}
			set
			{
				if ((this._MaKV != value))
				{
					this.OnMaKVChanging(value);
					this.SendPropertyChanging();
					this._MaKV = value;
					this.SendPropertyChanged("MaKV");
					this.OnMaKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int")]
		public System.Nullable<int> MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTN", DbType="TinyInt")]
		public System.Nullable<byte> MaTN
		{
			get
			{
				return this._MaTN;
			}
			set
			{
				if ((this._MaTN != value))
				{
					this.OnMaTNChanging(value);
					this.SendPropertyChanging();
					this._MaTN = value;
					this.SendPropertyChanged("MaTN");
					this.OnMaTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnKhachHang_SendMailNhacNo", Storage="_SendMailNhacNos", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<SendMailNhacNo> SendMailNhacNos
		{
			get
			{
				return this._SendMailNhacNos;
			}
			set
			{
				this._SendMailNhacNos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnKhachHang_SendMailDetail", Storage="_SendMailDetails", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<SendMailDetail> SendMailDetails
		{
			get
			{
				return this._SendMailDetails;
			}
			set
			{
				this._SendMailDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SendMailNhacNos(SendMailNhacNo entity)
		{
			this.SendPropertyChanging();
			entity.tnKhachHang = this;
		}
		
		private void detach_SendMailNhacNos(SendMailNhacNo entity)
		{
			this.SendPropertyChanging();
			entity.tnKhachHang = null;
		}
		
		private void attach_SendMailDetails(SendMailDetail entity)
		{
			this.SendPropertyChanging();
			entity.tnKhachHang = this;
		}
		
		private void detach_SendMailDetails(SendMailDetail entity)
		{
			this.SendPropertyChanging();
			entity.tnKhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SendMailNhacNo")]
	public partial class SendMailNhacNo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MailID;
		
		private string _TieuDe;
		
		private string _NoiDung;
		
		private System.Data.Linq.Binary _FileDinhKem;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<int> _MaNV;
		
		private System.Nullable<System.DateTime> _ThoiGianGui;
		
		private System.Nullable<int> _TrangThai;
		
		private System.Nullable<int> _MailFrom;
		
		private EntityRef<tnKhachHang> _tnKhachHang;
		
		private EntityRef<SendMailAccount> _SendMailAccount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMailIDChanging(int value);
    partial void OnMailIDChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnFileDinhKemChanging(System.Data.Linq.Binary value);
    partial void OnFileDinhKemChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnMaNVChanging(System.Nullable<int> value);
    partial void OnMaNVChanged();
    partial void OnThoiGianGuiChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianGuiChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    partial void OnMailFromChanging(System.Nullable<int> value);
    partial void OnMailFromChanged();
    #endregion
		
		public SendMailNhacNo()
		{
			this._tnKhachHang = default(EntityRef<tnKhachHang>);
			this._SendMailAccount = default(EntityRef<SendMailAccount>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MailID
		{
			get
			{
				return this._MailID;
			}
			set
			{
				if ((this._MailID != value))
				{
					this.OnMailIDChanging(value);
					this.SendPropertyChanging();
					this._MailID = value;
					this.SendPropertyChanged("MailID");
					this.OnMailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(100)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this.OnFileDinhKemChanging(value);
					this.SendPropertyChanging();
					this._FileDinhKem = value;
					this.SendPropertyChanged("FileDinhKem");
					this.OnFileDinhKemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tnKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int")]
		public System.Nullable<int> MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianGui", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianGui
		{
			get
			{
				return this._ThoiGianGui;
			}
			set
			{
				if ((this._ThoiGianGui != value))
				{
					this.OnThoiGianGuiChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianGui = value;
					this.SendPropertyChanged("ThoiGianGui");
					this.OnThoiGianGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailFrom", DbType="Int")]
		public System.Nullable<int> MailFrom
		{
			get
			{
				return this._MailFrom;
			}
			set
			{
				if ((this._MailFrom != value))
				{
					if (this._SendMailAccount.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMailFromChanging(value);
					this.SendPropertyChanging();
					this._MailFrom = value;
					this.SendPropertyChanged("MailFrom");
					this.OnMailFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnKhachHang_SendMailNhacNo", Storage="_tnKhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tnKhachHang tnKhachHang
		{
			get
			{
				return this._tnKhachHang.Entity;
			}
			set
			{
				tnKhachHang previousValue = this._tnKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tnKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tnKhachHang.Entity = null;
						previousValue.SendMailNhacNos.Remove(this);
					}
					this._tnKhachHang.Entity = value;
					if ((value != null))
					{
						value.SendMailNhacNos.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("tnKhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SendMailAccount_SendMailNhacNo", Storage="_SendMailAccount", ThisKey="MailFrom", OtherKey="ID", IsForeignKey=true)]
		public SendMailAccount SendMailAccount
		{
			get
			{
				return this._SendMailAccount.Entity;
			}
			set
			{
				SendMailAccount previousValue = this._SendMailAccount.Entity;
				if (((previousValue != value) 
							|| (this._SendMailAccount.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SendMailAccount.Entity = null;
						previousValue.SendMailNhacNos.Remove(this);
					}
					this._SendMailAccount.Entity = value;
					if ((value != null))
					{
						value.SendMailNhacNos.Add(this);
						this._MailFrom = value.ID;
					}
					else
					{
						this._MailFrom = default(Nullable<int>);
					}
					this.SendPropertyChanged("SendMailAccount");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SendMailDetail")]
	public partial class SendMailDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _MailID;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<int> _TrangThai;
		
		private EntityRef<tnKhachHang> _tnKhachHang;
		
		private EntityRef<SendMail> _SendMail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMailIDChanging(System.Nullable<int> value);
    partial void OnMailIDChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public SendMailDetail()
		{
			this._tnKhachHang = default(EntityRef<tnKhachHang>);
			this._SendMail = default(EntityRef<SendMail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailID", DbType="Int")]
		public System.Nullable<int> MailID
		{
			get
			{
				return this._MailID;
			}
			set
			{
				if ((this._MailID != value))
				{
					if (this._SendMail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMailIDChanging(value);
					this.SendPropertyChanging();
					this._MailID = value;
					this.SendPropertyChanged("MailID");
					this.OnMailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tnKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnKhachHang_SendMailDetail", Storage="_tnKhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tnKhachHang tnKhachHang
		{
			get
			{
				return this._tnKhachHang.Entity;
			}
			set
			{
				tnKhachHang previousValue = this._tnKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tnKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tnKhachHang.Entity = null;
						previousValue.SendMailDetails.Remove(this);
					}
					this._tnKhachHang.Entity = value;
					if ((value != null))
					{
						value.SendMailDetails.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("tnKhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SendMail_SendMailDetail", Storage="_SendMail", ThisKey="MailID", OtherKey="MailID", IsForeignKey=true, DeleteRule="CASCADE")]
		public SendMail SendMail
		{
			get
			{
				return this._SendMail.Entity;
			}
			set
			{
				SendMail previousValue = this._SendMail.Entity;
				if (((previousValue != value) 
							|| (this._SendMail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SendMail.Entity = null;
						previousValue.SendMailDetails.Remove(this);
					}
					this._SendMail.Entity = value;
					if ((value != null))
					{
						value.SendMailDetails.Add(this);
						this._MailID = value.MailID;
					}
					else
					{
						this._MailID = default(Nullable<int>);
					}
					this.SendPropertyChanged("SendMail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SendMailAccount")]
	public partial class SendMailAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DiaChi;
		
		private string _Server;
		
		private string _Username;
		
		private string _Password;
		
		private System.Nullable<int> _Port;
		
		private EntitySet<SendMailNhacNo> _SendMailNhacNos;
		
		private EntitySet<SendMail> _SendMails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnServerChanging(string value);
    partial void OnServerChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPortChanging(System.Nullable<int> value);
    partial void OnPortChanged();
    #endregion
		
		public SendMailAccount()
		{
			this._SendMailNhacNos = new EntitySet<SendMailNhacNo>(new Action<SendMailNhacNo>(this.attach_SendMailNhacNos), new Action<SendMailNhacNo>(this.detach_SendMailNhacNos));
			this._SendMails = new EntitySet<SendMail>(new Action<SendMail>(this.attach_SendMails), new Action<SendMail>(this.detach_SendMails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Server", DbType="NVarChar(50)")]
		public string Server
		{
			get
			{
				return this._Server;
			}
			set
			{
				if ((this._Server != value))
				{
					this.OnServerChanging(value);
					this.SendPropertyChanging();
					this._Server = value;
					this.SendPropertyChanged("Server");
					this.OnServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port", DbType="Int")]
		public System.Nullable<int> Port
		{
			get
			{
				return this._Port;
			}
			set
			{
				if ((this._Port != value))
				{
					this.OnPortChanging(value);
					this.SendPropertyChanging();
					this._Port = value;
					this.SendPropertyChanged("Port");
					this.OnPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SendMailAccount_SendMailNhacNo", Storage="_SendMailNhacNos", ThisKey="ID", OtherKey="MailFrom")]
		public EntitySet<SendMailNhacNo> SendMailNhacNos
		{
			get
			{
				return this._SendMailNhacNos;
			}
			set
			{
				this._SendMailNhacNos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SendMailAccount_SendMail", Storage="_SendMails", ThisKey="ID", OtherKey="MailFrom")]
		public EntitySet<SendMail> SendMails
		{
			get
			{
				return this._SendMails;
			}
			set
			{
				this._SendMails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SendMailNhacNos(SendMailNhacNo entity)
		{
			this.SendPropertyChanging();
			entity.SendMailAccount = this;
		}
		
		private void detach_SendMailNhacNos(SendMailNhacNo entity)
		{
			this.SendPropertyChanging();
			entity.SendMailAccount = null;
		}
		
		private void attach_SendMails(SendMail entity)
		{
			this.SendPropertyChanging();
			entity.SendMailAccount = this;
		}
		
		private void detach_SendMails(SendMail entity)
		{
			this.SendPropertyChanging();
			entity.SendMailAccount = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SendMail")]
	public partial class SendMail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MailID;
		
		private string _TieuDe;
		
		private string _NoiDung;
		
		private System.Nullable<int> _MaNV;
		
		private System.Nullable<System.DateTime> _ThoiGianGui;
		
		private System.Nullable<int> _MailFrom;
		
		private EntitySet<SendMailDetail> _SendMailDetails;
		
		private EntityRef<SendMailAccount> _SendMailAccount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMailIDChanging(int value);
    partial void OnMailIDChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnMaNVChanging(System.Nullable<int> value);
    partial void OnMaNVChanged();
    partial void OnThoiGianGuiChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianGuiChanged();
    partial void OnMailFromChanging(System.Nullable<int> value);
    partial void OnMailFromChanged();
    #endregion
		
		public SendMail()
		{
			this._SendMailDetails = new EntitySet<SendMailDetail>(new Action<SendMailDetail>(this.attach_SendMailDetails), new Action<SendMailDetail>(this.detach_SendMailDetails));
			this._SendMailAccount = default(EntityRef<SendMailAccount>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MailID
		{
			get
			{
				return this._MailID;
			}
			set
			{
				if ((this._MailID != value))
				{
					this.OnMailIDChanging(value);
					this.SendPropertyChanging();
					this._MailID = value;
					this.SendPropertyChanged("MailID");
					this.OnMailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(50)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int")]
		public System.Nullable<int> MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianGui", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianGui
		{
			get
			{
				return this._ThoiGianGui;
			}
			set
			{
				if ((this._ThoiGianGui != value))
				{
					this.OnThoiGianGuiChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianGui = value;
					this.SendPropertyChanged("ThoiGianGui");
					this.OnThoiGianGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailFrom", DbType="Int")]
		public System.Nullable<int> MailFrom
		{
			get
			{
				return this._MailFrom;
			}
			set
			{
				if ((this._MailFrom != value))
				{
					if (this._SendMailAccount.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMailFromChanging(value);
					this.SendPropertyChanging();
					this._MailFrom = value;
					this.SendPropertyChanged("MailFrom");
					this.OnMailFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SendMail_SendMailDetail", Storage="_SendMailDetails", ThisKey="MailID", OtherKey="MailID")]
		public EntitySet<SendMailDetail> SendMailDetails
		{
			get
			{
				return this._SendMailDetails;
			}
			set
			{
				this._SendMailDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SendMailAccount_SendMail", Storage="_SendMailAccount", ThisKey="MailFrom", OtherKey="ID", IsForeignKey=true)]
		public SendMailAccount SendMailAccount
		{
			get
			{
				return this._SendMailAccount.Entity;
			}
			set
			{
				SendMailAccount previousValue = this._SendMailAccount.Entity;
				if (((previousValue != value) 
							|| (this._SendMailAccount.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SendMailAccount.Entity = null;
						previousValue.SendMails.Remove(this);
					}
					this._SendMailAccount.Entity = value;
					if ((value != null))
					{
						value.SendMails.Add(this);
						this._MailFrom = value.ID;
					}
					else
					{
						this._MailFrom = default(Nullable<int>);
					}
					this.SendPropertyChanged("SendMailAccount");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SendMailDetails(SendMailDetail entity)
		{
			this.SendPropertyChanging();
			entity.SendMail = this;
		}
		
		private void detach_SendMailDetails(SendMailDetail entity)
		{
			this.SendPropertyChanging();
			entity.SendMail = null;
		}
	}
}
#pragma warning restore 1591
