#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTTCNew
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Building_TTC_db")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttnycCaiDat(tnycCaiDat instance);
    partial void UpdatetnycCaiDat(tnycCaiDat instance);
    partial void DeletetnycCaiDat(tnycCaiDat instance);
    partial void InserttnycYeuCau_Thread(tnycYeuCau_Thread instance);
    partial void UpdatetnycYeuCau_Thread(tnycYeuCau_Thread instance);
    partial void DeletetnycYeuCau_Thread(tnycYeuCau_Thread instance);
    partial void InserttnycDoUuTien(tnycDoUuTien instance);
    partial void UpdatetnycDoUuTien(tnycDoUuTien instance);
    partial void DeletetnycDoUuTien(tnycDoUuTien instance);
    partial void InserttnycHinhAnh(tnycHinhAnh instance);
    partial void UpdatetnycHinhAnh(tnycHinhAnh instance);
    partial void DeletetnycHinhAnh(tnycHinhAnh instance);
    partial void InserttnycImgNhanVienUpload(tnycImgNhanVienUpload instance);
    partial void UpdatetnycImgNhanVienUpload(tnycImgNhanVienUpload instance);
    partial void DeletetnycImgNhanVienUpload(tnycImgNhanVienUpload instance);
    partial void InserttnycLichSuCapNhat(tnycLichSuCapNhat instance);
    partial void UpdatetnycLichSuCapNhat(tnycLichSuCapNhat instance);
    partial void DeletetnycLichSuCapNhat(tnycLichSuCapNhat instance);
    partial void InserttnycLoaiYeuCau(tnycLoaiYeuCau instance);
    partial void UpdatetnycLoaiYeuCau(tnycLoaiYeuCau instance);
    partial void DeletetnycLoaiYeuCau(tnycLoaiYeuCau instance);
    partial void InserttnycNguonDen(tnycNguonDen instance);
    partial void UpdatetnycNguonDen(tnycNguonDen instance);
    partial void DeletetnycNguonDen(tnycNguonDen instance);
    partial void InserttnycThongBao(tnycThongBao instance);
    partial void UpdatetnycThongBao(tnycThongBao instance);
    partial void DeletetnycThongBao(tnycThongBao instance);
    partial void InserttnycTrangThai(tnycTrangThai instance);
    partial void UpdatetnycTrangThai(tnycTrangThai instance);
    partial void DeletetnycTrangThai(tnycTrangThai instance);
    partial void InserttnycYeuCau(tnycYeuCau instance);
    partial void UpdatetnycYeuCau(tnycYeuCau instance);
    partial void DeletetnycYeuCau(tnycYeuCau instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ServiceTTCNew.Properties.Settings.Default.Building_TTC_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tnycCaiDat> tnycCaiDats
		{
			get
			{
				return this.GetTable<tnycCaiDat>();
			}
		}
		
		public System.Data.Linq.Table<tnycYeuCau_Thread> tnycYeuCau_Threads
		{
			get
			{
				return this.GetTable<tnycYeuCau_Thread>();
			}
		}
		
		public System.Data.Linq.Table<tnycDoUuTien> tnycDoUuTiens
		{
			get
			{
				return this.GetTable<tnycDoUuTien>();
			}
		}
		
		public System.Data.Linq.Table<tnycHinhAnh> tnycHinhAnhs
		{
			get
			{
				return this.GetTable<tnycHinhAnh>();
			}
		}
		
		public System.Data.Linq.Table<tnycImgNhanVienUpload> tnycImgNhanVienUploads
		{
			get
			{
				return this.GetTable<tnycImgNhanVienUpload>();
			}
		}
		
		public System.Data.Linq.Table<tnycLichSuCapNhat> tnycLichSuCapNhats
		{
			get
			{
				return this.GetTable<tnycLichSuCapNhat>();
			}
		}
		
		public System.Data.Linq.Table<tnycLoaiYeuCau> tnycLoaiYeuCaus
		{
			get
			{
				return this.GetTable<tnycLoaiYeuCau>();
			}
		}
		
		public System.Data.Linq.Table<tnycNguonDen> tnycNguonDens
		{
			get
			{
				return this.GetTable<tnycNguonDen>();
			}
		}
		
		public System.Data.Linq.Table<tnycThongBao> tnycThongBaos
		{
			get
			{
				return this.GetTable<tnycThongBao>();
			}
		}
		
		public System.Data.Linq.Table<tnycTrangThai> tnycTrangThais
		{
			get
			{
				return this.GetTable<tnycTrangThai>();
			}
		}
		
		public System.Data.Linq.Table<tnycYeuCau> tnycYeuCaus
		{
			get
			{
				return this.GetTable<tnycYeuCau>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycCaiDat")]
	public partial class tnycCaiDat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<byte> _MaTN;
		
		private System.Nullable<int> _MaPB;
		
		private System.Nullable<int> _MaNV;
		
		private System.Nullable<bool> _IsMail;
		
		private System.Nullable<bool> _IsSMS;
		
		private System.Nullable<bool> _IsRemind;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaTNChanging(System.Nullable<byte> value);
    partial void OnMaTNChanged();
    partial void OnMaPBChanging(System.Nullable<int> value);
    partial void OnMaPBChanged();
    partial void OnMaNVChanging(System.Nullable<int> value);
    partial void OnMaNVChanged();
    partial void OnIsMailChanging(System.Nullable<bool> value);
    partial void OnIsMailChanged();
    partial void OnIsSMSChanging(System.Nullable<bool> value);
    partial void OnIsSMSChanged();
    partial void OnIsRemindChanging(System.Nullable<bool> value);
    partial void OnIsRemindChanged();
    #endregion
		
		public tnycCaiDat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTN", DbType="TinyInt")]
		public System.Nullable<byte> MaTN
		{
			get
			{
				return this._MaTN;
			}
			set
			{
				if ((this._MaTN != value))
				{
					this.OnMaTNChanging(value);
					this.SendPropertyChanging();
					this._MaTN = value;
					this.SendPropertyChanged("MaTN");
					this.OnMaTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPB", DbType="Int")]
		public System.Nullable<int> MaPB
		{
			get
			{
				return this._MaPB;
			}
			set
			{
				if ((this._MaPB != value))
				{
					this.OnMaPBChanging(value);
					this.SendPropertyChanging();
					this._MaPB = value;
					this.SendPropertyChanged("MaPB");
					this.OnMaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int")]
		public System.Nullable<int> MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMail", DbType="Bit")]
		public System.Nullable<bool> IsMail
		{
			get
			{
				return this._IsMail;
			}
			set
			{
				if ((this._IsMail != value))
				{
					this.OnIsMailChanging(value);
					this.SendPropertyChanging();
					this._IsMail = value;
					this.SendPropertyChanged("IsMail");
					this.OnIsMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSMS", DbType="Bit")]
		public System.Nullable<bool> IsSMS
		{
			get
			{
				return this._IsSMS;
			}
			set
			{
				if ((this._IsSMS != value))
				{
					this.OnIsSMSChanging(value);
					this.SendPropertyChanging();
					this._IsSMS = value;
					this.SendPropertyChanged("IsSMS");
					this.OnIsSMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRemind", DbType="Bit")]
		public System.Nullable<bool> IsRemind
		{
			get
			{
				return this._IsRemind;
			}
			set
			{
				if ((this._IsRemind != value))
				{
					this.OnIsRemindChanging(value);
					this.SendPropertyChanging();
					this._IsRemind = value;
					this.SendPropertyChanged("IsRemind");
					this.OnIsRemindChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycYeuCau_Thread")]
	public partial class tnycYeuCau_Thread : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _YeuCauID;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _NgayThang;
		
		private System.Nullable<int> _MaNV;
		
		private string _NguyenNhan;
		
		private string _BienPhapXuLy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnYeuCauIDChanging(System.Nullable<int> value);
    partial void OnYeuCauIDChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayThangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThangChanged();
    partial void OnMaNVChanging(System.Nullable<int> value);
    partial void OnMaNVChanged();
    partial void OnNguyenNhanChanging(string value);
    partial void OnNguyenNhanChanged();
    partial void OnBienPhapXuLyChanging(string value);
    partial void OnBienPhapXuLyChanged();
    #endregion
		
		public tnycYeuCau_Thread()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauID", DbType="Int")]
		public System.Nullable<int> YeuCauID
		{
			get
			{
				return this._YeuCauID;
			}
			set
			{
				if ((this._YeuCauID != value))
				{
					this.OnYeuCauIDChanging(value);
					this.SendPropertyChanging();
					this._YeuCauID = value;
					this.SendPropertyChanged("YeuCauID");
					this.OnYeuCauIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(1000)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThang
		{
			get
			{
				return this._NgayThang;
			}
			set
			{
				if ((this._NgayThang != value))
				{
					this.OnNgayThangChanging(value);
					this.SendPropertyChanging();
					this._NgayThang = value;
					this.SendPropertyChanged("NgayThang");
					this.OnNgayThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int")]
		public System.Nullable<int> MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguyenNhan", DbType="NVarChar(1000)")]
		public string NguyenNhan
		{
			get
			{
				return this._NguyenNhan;
			}
			set
			{
				if ((this._NguyenNhan != value))
				{
					this.OnNguyenNhanChanging(value);
					this.SendPropertyChanging();
					this._NguyenNhan = value;
					this.SendPropertyChanged("NguyenNhan");
					this.OnNguyenNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BienPhapXuLy", DbType="NVarChar(1000)")]
		public string BienPhapXuLy
		{
			get
			{
				return this._BienPhapXuLy;
			}
			set
			{
				if ((this._BienPhapXuLy != value))
				{
					this.OnBienPhapXuLyChanging(value);
					this.SendPropertyChanging();
					this._BienPhapXuLy = value;
					this.SendPropertyChanged("BienPhapXuLy");
					this.OnBienPhapXuLyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycDoUuTien")]
	public partial class tnycDoUuTien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDoUuTien;
		
		private string _TenDoUuTien;
		
		private System.Nullable<int> _MauNen;
		
		private EntitySet<tnycYeuCau> _tnycYeuCaus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDoUuTienChanging(int value);
    partial void OnMaDoUuTienChanged();
    partial void OnTenDoUuTienChanging(string value);
    partial void OnTenDoUuTienChanged();
    partial void OnMauNenChanging(System.Nullable<int> value);
    partial void OnMauNenChanged();
    #endregion
		
		public tnycDoUuTien()
		{
			this._tnycYeuCaus = new EntitySet<tnycYeuCau>(new Action<tnycYeuCau>(this.attach_tnycYeuCaus), new Action<tnycYeuCau>(this.detach_tnycYeuCaus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoUuTien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDoUuTien
		{
			get
			{
				return this._MaDoUuTien;
			}
			set
			{
				if ((this._MaDoUuTien != value))
				{
					this.OnMaDoUuTienChanging(value);
					this.SendPropertyChanging();
					this._MaDoUuTien = value;
					this.SendPropertyChanged("MaDoUuTien");
					this.OnMaDoUuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoUuTien", DbType="NVarChar(50)")]
		public string TenDoUuTien
		{
			get
			{
				return this._TenDoUuTien;
			}
			set
			{
				if ((this._TenDoUuTien != value))
				{
					this.OnTenDoUuTienChanging(value);
					this.SendPropertyChanging();
					this._TenDoUuTien = value;
					this.SendPropertyChanged("TenDoUuTien");
					this.OnTenDoUuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauNen", DbType="Int")]
		public System.Nullable<int> MauNen
		{
			get
			{
				return this._MauNen;
			}
			set
			{
				if ((this._MauNen != value))
				{
					this.OnMauNenChanging(value);
					this.SendPropertyChanging();
					this._MauNen = value;
					this.SendPropertyChanged("MauNen");
					this.OnMauNenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycDoUuTien_tnycYeuCau", Storage="_tnycYeuCaus", ThisKey="MaDoUuTien", OtherKey="MaDoUuTien")]
		public EntitySet<tnycYeuCau> tnycYeuCaus
		{
			get
			{
				return this._tnycYeuCaus;
			}
			set
			{
				this._tnycYeuCaus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tnycYeuCaus(tnycYeuCau entity)
		{
			this.SendPropertyChanging();
			entity.tnycDoUuTien = this;
		}
		
		private void detach_tnycYeuCaus(tnycYeuCau entity)
		{
			this.SendPropertyChanging();
			entity.tnycDoUuTien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycHinhAnh")]
	public partial class tnycHinhAnh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _MaYC;
		
		private string _URL;
		
		private string _thumbnail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaYCChanging(System.Nullable<int> value);
    partial void OnMaYCChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnthumbnailChanging(string value);
    partial void OnthumbnailChanged();
    #endregion
		
		public tnycHinhAnh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaYC", DbType="Int")]
		public System.Nullable<int> MaYC
		{
			get
			{
				return this._MaYC;
			}
			set
			{
				if ((this._MaYC != value))
				{
					this.OnMaYCChanging(value);
					this.SendPropertyChanging();
					this._MaYC = value;
					this.SendPropertyChanged("MaYC");
					this.OnMaYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(300)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thumbnail", DbType="NVarChar(300)")]
		public string thumbnail
		{
			get
			{
				return this._thumbnail;
			}
			set
			{
				if ((this._thumbnail != value))
				{
					this.OnthumbnailChanging(value);
					this.SendPropertyChanging();
					this._thumbnail = value;
					this.SendPropertyChanged("thumbnail");
					this.OnthumbnailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycImgNhanVienUpload")]
	public partial class tnycImgNhanVienUpload : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _MaYC;
		
		private string _URL;
		
		private string _thumbnail;
		
		private System.Nullable<int> _IDLichSuYeuCau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaYCChanging(System.Nullable<int> value);
    partial void OnMaYCChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnthumbnailChanging(string value);
    partial void OnthumbnailChanged();
    partial void OnIDLichSuYeuCauChanging(System.Nullable<int> value);
    partial void OnIDLichSuYeuCauChanged();
    #endregion
		
		public tnycImgNhanVienUpload()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaYC", DbType="Int")]
		public System.Nullable<int> MaYC
		{
			get
			{
				return this._MaYC;
			}
			set
			{
				if ((this._MaYC != value))
				{
					this.OnMaYCChanging(value);
					this.SendPropertyChanging();
					this._MaYC = value;
					this.SendPropertyChanged("MaYC");
					this.OnMaYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(MAX)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thumbnail", DbType="NVarChar(300)")]
		public string thumbnail
		{
			get
			{
				return this._thumbnail;
			}
			set
			{
				if ((this._thumbnail != value))
				{
					this.OnthumbnailChanging(value);
					this.SendPropertyChanging();
					this._thumbnail = value;
					this.SendPropertyChanged("thumbnail");
					this.OnthumbnailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLichSuYeuCau", DbType="Int")]
		public System.Nullable<int> IDLichSuYeuCau
		{
			get
			{
				return this._IDLichSuYeuCau;
			}
			set
			{
				if ((this._IDLichSuYeuCau != value))
				{
					this.OnIDLichSuYeuCauChanging(value);
					this.SendPropertyChanging();
					this._IDLichSuYeuCau = value;
					this.SendPropertyChanged("IDLichSuYeuCau");
					this.OnIDLichSuYeuCauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycLichSuCapNhat")]
	public partial class tnycLichSuCapNhat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _MaYC;
		
		private System.Nullable<int> _MaNV;
		
		private System.Nullable<System.DateTime> _NgayCN;
		
		private System.Nullable<int> _MaTT;
		
		private string _NoiDung;
		
		private string _NguyenNhan;
		
		private string _BienPhapXuLy;
		
		private string _NhanVien;
		
		private string _YKienCH;
		
		private System.Nullable<int> _MaPB;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<bool> _isKH;
		
		private System.Nullable<System.DateTime> _NgayHetHanDauTien;
		
		private System.Nullable<System.DateTime> _NgayHetHanCuoiCung;
		
		private System.Nullable<System.DateTime> _NgayGiaHan;
		
		private string _LyDoGiaHan;
		
		private System.Nullable<byte> _RatingMark;
		
		private EntityRef<tnycTrangThai> _tnycTrangThai;
		
		private EntityRef<tnycYeuCau> _tnycYeuCau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaYCChanging(System.Nullable<int> value);
    partial void OnMaYCChanged();
    partial void OnMaNVChanging(System.Nullable<int> value);
    partial void OnMaNVChanged();
    partial void OnNgayCNChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCNChanged();
    partial void OnMaTTChanging(System.Nullable<int> value);
    partial void OnMaTTChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNguyenNhanChanging(string value);
    partial void OnNguyenNhanChanged();
    partial void OnBienPhapXuLyChanging(string value);
    partial void OnBienPhapXuLyChanged();
    partial void OnNhanVienChanging(string value);
    partial void OnNhanVienChanged();
    partial void OnYKienCHChanging(string value);
    partial void OnYKienCHChanged();
    partial void OnMaPBChanging(System.Nullable<int> value);
    partial void OnMaPBChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnisKHChanging(System.Nullable<bool> value);
    partial void OnisKHChanged();
    partial void OnNgayHetHanDauTienChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanDauTienChanged();
    partial void OnNgayHetHanCuoiCungChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanCuoiCungChanged();
    partial void OnNgayGiaHanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaHanChanged();
    partial void OnLyDoGiaHanChanging(string value);
    partial void OnLyDoGiaHanChanged();
    partial void OnRatingMarkChanging(System.Nullable<byte> value);
    partial void OnRatingMarkChanged();
    #endregion
		
		public tnycLichSuCapNhat()
		{
			this._tnycTrangThai = default(EntityRef<tnycTrangThai>);
			this._tnycYeuCau = default(EntityRef<tnycYeuCau>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaYC", DbType="Int")]
		public System.Nullable<int> MaYC
		{
			get
			{
				return this._MaYC;
			}
			set
			{
				if ((this._MaYC != value))
				{
					if (this._tnycYeuCau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaYCChanging(value);
					this.SendPropertyChanging();
					this._MaYC = value;
					this.SendPropertyChanged("MaYC");
					this.OnMaYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int")]
		public System.Nullable<int> MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCN
		{
			get
			{
				return this._NgayCN;
			}
			set
			{
				if ((this._NgayCN != value))
				{
					this.OnNgayCNChanging(value);
					this.SendPropertyChanging();
					this._NgayCN = value;
					this.SendPropertyChanged("NgayCN");
					this.OnNgayCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="Int")]
		public System.Nullable<int> MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					if (this._tnycTrangThai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(1000)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguyenNhan", DbType="NVarChar(1000)")]
		public string NguyenNhan
		{
			get
			{
				return this._NguyenNhan;
			}
			set
			{
				if ((this._NguyenNhan != value))
				{
					this.OnNguyenNhanChanging(value);
					this.SendPropertyChanging();
					this._NguyenNhan = value;
					this.SendPropertyChanged("NguyenNhan");
					this.OnNguyenNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BienPhapXuLy", DbType="NVarChar(1000)")]
		public string BienPhapXuLy
		{
			get
			{
				return this._BienPhapXuLy;
			}
			set
			{
				if ((this._BienPhapXuLy != value))
				{
					this.OnBienPhapXuLyChanging(value);
					this.SendPropertyChanging();
					this._BienPhapXuLy = value;
					this.SendPropertyChanged("BienPhapXuLy");
					this.OnBienPhapXuLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVien", DbType="NVarChar(1000)")]
		public string NhanVien
		{
			get
			{
				return this._NhanVien;
			}
			set
			{
				if ((this._NhanVien != value))
				{
					this.OnNhanVienChanging(value);
					this.SendPropertyChanging();
					this._NhanVien = value;
					this.SendPropertyChanged("NhanVien");
					this.OnNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YKienCH", DbType="NVarChar(1000)")]
		public string YKienCH
		{
			get
			{
				return this._YKienCH;
			}
			set
			{
				if ((this._YKienCH != value))
				{
					this.OnYKienCHChanging(value);
					this.SendPropertyChanging();
					this._YKienCH = value;
					this.SendPropertyChanged("YKienCH");
					this.OnYKienCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPB", DbType="Int")]
		public System.Nullable<int> MaPB
		{
			get
			{
				return this._MaPB;
			}
			set
			{
				if ((this._MaPB != value))
				{
					this.OnMaPBChanging(value);
					this.SendPropertyChanging();
					this._MaPB = value;
					this.SendPropertyChanged("MaPB");
					this.OnMaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isKH", DbType="Bit")]
		public System.Nullable<bool> isKH
		{
			get
			{
				return this._isKH;
			}
			set
			{
				if ((this._isKH != value))
				{
					this.OnisKHChanging(value);
					this.SendPropertyChanging();
					this._isKH = value;
					this.SendPropertyChanged("isKH");
					this.OnisKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHanDauTien", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHanDauTien
		{
			get
			{
				return this._NgayHetHanDauTien;
			}
			set
			{
				if ((this._NgayHetHanDauTien != value))
				{
					this.OnNgayHetHanDauTienChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHanDauTien = value;
					this.SendPropertyChanged("NgayHetHanDauTien");
					this.OnNgayHetHanDauTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHanCuoiCung", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHanCuoiCung
		{
			get
			{
				return this._NgayHetHanCuoiCung;
			}
			set
			{
				if ((this._NgayHetHanCuoiCung != value))
				{
					this.OnNgayHetHanCuoiCungChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHanCuoiCung = value;
					this.SendPropertyChanged("NgayHetHanCuoiCung");
					this.OnNgayHetHanCuoiCungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaHan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGiaHan
		{
			get
			{
				return this._NgayGiaHan;
			}
			set
			{
				if ((this._NgayGiaHan != value))
				{
					this.OnNgayGiaHanChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaHan = value;
					this.SendPropertyChanged("NgayGiaHan");
					this.OnNgayGiaHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDoGiaHan", DbType="NVarChar(500)")]
		public string LyDoGiaHan
		{
			get
			{
				return this._LyDoGiaHan;
			}
			set
			{
				if ((this._LyDoGiaHan != value))
				{
					this.OnLyDoGiaHanChanging(value);
					this.SendPropertyChanging();
					this._LyDoGiaHan = value;
					this.SendPropertyChanged("LyDoGiaHan");
					this.OnLyDoGiaHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RatingMark", DbType="TinyInt")]
		public System.Nullable<byte> RatingMark
		{
			get
			{
				return this._RatingMark;
			}
			set
			{
				if ((this._RatingMark != value))
				{
					this.OnRatingMarkChanging(value);
					this.SendPropertyChanging();
					this._RatingMark = value;
					this.SendPropertyChanged("RatingMark");
					this.OnRatingMarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycTrangThai_tnycLichSuCapNhat", Storage="_tnycTrangThai", ThisKey="MaTT", OtherKey="MaTT", IsForeignKey=true)]
		public tnycTrangThai tnycTrangThai
		{
			get
			{
				return this._tnycTrangThai.Entity;
			}
			set
			{
				tnycTrangThai previousValue = this._tnycTrangThai.Entity;
				if (((previousValue != value) 
							|| (this._tnycTrangThai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tnycTrangThai.Entity = null;
						previousValue.tnycLichSuCapNhats.Remove(this);
					}
					this._tnycTrangThai.Entity = value;
					if ((value != null))
					{
						value.tnycLichSuCapNhats.Add(this);
						this._MaTT = value.MaTT;
					}
					else
					{
						this._MaTT = default(Nullable<int>);
					}
					this.SendPropertyChanged("tnycTrangThai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycYeuCau_tnycLichSuCapNhat", Storage="_tnycYeuCau", ThisKey="MaYC", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public tnycYeuCau tnycYeuCau
		{
			get
			{
				return this._tnycYeuCau.Entity;
			}
			set
			{
				tnycYeuCau previousValue = this._tnycYeuCau.Entity;
				if (((previousValue != value) 
							|| (this._tnycYeuCau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tnycYeuCau.Entity = null;
						previousValue.tnycLichSuCapNhats.Remove(this);
					}
					this._tnycYeuCau.Entity = value;
					if ((value != null))
					{
						value.tnycLichSuCapNhats.Add(this);
						this._MaYC = value.ID;
					}
					else
					{
						this._MaYC = default(Nullable<int>);
					}
					this.SendPropertyChanged("tnycYeuCau");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycLoaiYeuCau")]
	public partial class tnycLoaiYeuCau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenLoaiYeuCau;
		
		private string _TenVT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenLoaiYeuCauChanging(string value);
    partial void OnTenLoaiYeuCauChanged();
    partial void OnTenVTChanging(string value);
    partial void OnTenVTChanged();
    #endregion
		
		public tnycLoaiYeuCau()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiYeuCau", DbType="NVarChar(255)")]
		public string TenLoaiYeuCau
		{
			get
			{
				return this._TenLoaiYeuCau;
			}
			set
			{
				if ((this._TenLoaiYeuCau != value))
				{
					this.OnTenLoaiYeuCauChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiYeuCau = value;
					this.SendPropertyChanged("TenLoaiYeuCau");
					this.OnTenLoaiYeuCauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVT", DbType="NVarChar(255)")]
		public string TenVT
		{
			get
			{
				return this._TenVT;
			}
			set
			{
				if ((this._TenVT != value))
				{
					this.OnTenVTChanging(value);
					this.SendPropertyChanging();
					this._TenVT = value;
					this.SendPropertyChanged("TenVT");
					this.OnTenVTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycNguonDen")]
	public partial class tnycNguonDen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenNguonDen;
		
		private System.Nullable<int> _STT;
		
		private EntitySet<tnycYeuCau> _tnycYeuCaus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenNguonDenChanging(string value);
    partial void OnTenNguonDenChanged();
    partial void OnSTTChanging(System.Nullable<int> value);
    partial void OnSTTChanged();
    #endregion
		
		public tnycNguonDen()
		{
			this._tnycYeuCaus = new EntitySet<tnycYeuCau>(new Action<tnycYeuCau>(this.attach_tnycYeuCaus), new Action<tnycYeuCau>(this.detach_tnycYeuCaus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguonDen", DbType="NVarChar(50)")]
		public string TenNguonDen
		{
			get
			{
				return this._TenNguonDen;
			}
			set
			{
				if ((this._TenNguonDen != value))
				{
					this.OnTenNguonDenChanging(value);
					this.SendPropertyChanging();
					this._TenNguonDen = value;
					this.SendPropertyChanged("TenNguonDen");
					this.OnTenNguonDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycNguonDen_tnycYeuCau", Storage="_tnycYeuCaus", ThisKey="ID", OtherKey="MaNguonDen")]
		public EntitySet<tnycYeuCau> tnycYeuCaus
		{
			get
			{
				return this._tnycYeuCaus;
			}
			set
			{
				this._tnycYeuCaus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tnycYeuCaus(tnycYeuCau entity)
		{
			this.SendPropertyChanging();
			entity.tnycNguonDen = this;
		}
		
		private void detach_tnycYeuCaus(tnycYeuCau entity)
		{
			this.SendPropertyChanging();
			entity.tnycNguonDen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycThongBao")]
	public partial class tnycThongBao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _MaYC;
		
		private System.Nullable<System.DateTime> _NgayBD;
		
		private System.Nullable<System.DateTime> _NgayKT;
		
		private System.Nullable<System.DateTime> _NgayNhac;
		
		private System.Nullable<int> _MaNV;
		
		private System.Nullable<bool> _IsNhac;
		
		private System.Nullable<byte> _TimeID;
		
		private System.Nullable<byte> _TimeID2;
		
		private System.Nullable<bool> _IsRepeat;
		
		private System.Nullable<bool> _DaNhac;
		
		private EntityRef<tnycYeuCau> _tnycYeuCau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaYCChanging(System.Nullable<int> value);
    partial void OnMaYCChanged();
    partial void OnNgayBDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBDChanged();
    partial void OnNgayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKTChanged();
    partial void OnNgayNhacChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhacChanged();
    partial void OnMaNVChanging(System.Nullable<int> value);
    partial void OnMaNVChanged();
    partial void OnIsNhacChanging(System.Nullable<bool> value);
    partial void OnIsNhacChanged();
    partial void OnTimeIDChanging(System.Nullable<byte> value);
    partial void OnTimeIDChanged();
    partial void OnTimeID2Changing(System.Nullable<byte> value);
    partial void OnTimeID2Changed();
    partial void OnIsRepeatChanging(System.Nullable<bool> value);
    partial void OnIsRepeatChanged();
    partial void OnDaNhacChanging(System.Nullable<bool> value);
    partial void OnDaNhacChanged();
    #endregion
		
		public tnycThongBao()
		{
			this._tnycYeuCau = default(EntityRef<tnycYeuCau>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaYC", DbType="Int")]
		public System.Nullable<int> MaYC
		{
			get
			{
				return this._MaYC;
			}
			set
			{
				if ((this._MaYC != value))
				{
					if (this._tnycYeuCau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaYCChanging(value);
					this.SendPropertyChanging();
					this._MaYC = value;
					this.SendPropertyChanged("MaYC");
					this.OnMaYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBD
		{
			get
			{
				return this._NgayBD;
			}
			set
			{
				if ((this._NgayBD != value))
				{
					this.OnNgayBDChanging(value);
					this.SendPropertyChanging();
					this._NgayBD = value;
					this.SendPropertyChanged("NgayBD");
					this.OnNgayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKT
		{
			get
			{
				return this._NgayKT;
			}
			set
			{
				if ((this._NgayKT != value))
				{
					this.OnNgayKTChanging(value);
					this.SendPropertyChanging();
					this._NgayKT = value;
					this.SendPropertyChanged("NgayKT");
					this.OnNgayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhac", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNhac
		{
			get
			{
				return this._NgayNhac;
			}
			set
			{
				if ((this._NgayNhac != value))
				{
					this.OnNgayNhacChanging(value);
					this.SendPropertyChanging();
					this._NgayNhac = value;
					this.SendPropertyChanged("NgayNhac");
					this.OnNgayNhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int")]
		public System.Nullable<int> MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNhac", DbType="Bit")]
		public System.Nullable<bool> IsNhac
		{
			get
			{
				return this._IsNhac;
			}
			set
			{
				if ((this._IsNhac != value))
				{
					this.OnIsNhacChanging(value);
					this.SendPropertyChanging();
					this._IsNhac = value;
					this.SendPropertyChanged("IsNhac");
					this.OnIsNhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeID", DbType="TinyInt")]
		public System.Nullable<byte> TimeID
		{
			get
			{
				return this._TimeID;
			}
			set
			{
				if ((this._TimeID != value))
				{
					this.OnTimeIDChanging(value);
					this.SendPropertyChanging();
					this._TimeID = value;
					this.SendPropertyChanged("TimeID");
					this.OnTimeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeID2", DbType="TinyInt")]
		public System.Nullable<byte> TimeID2
		{
			get
			{
				return this._TimeID2;
			}
			set
			{
				if ((this._TimeID2 != value))
				{
					this.OnTimeID2Changing(value);
					this.SendPropertyChanging();
					this._TimeID2 = value;
					this.SendPropertyChanged("TimeID2");
					this.OnTimeID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRepeat", DbType="Bit")]
		public System.Nullable<bool> IsRepeat
		{
			get
			{
				return this._IsRepeat;
			}
			set
			{
				if ((this._IsRepeat != value))
				{
					this.OnIsRepeatChanging(value);
					this.SendPropertyChanging();
					this._IsRepeat = value;
					this.SendPropertyChanged("IsRepeat");
					this.OnIsRepeatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaNhac", DbType="Bit")]
		public System.Nullable<bool> DaNhac
		{
			get
			{
				return this._DaNhac;
			}
			set
			{
				if ((this._DaNhac != value))
				{
					this.OnDaNhacChanging(value);
					this.SendPropertyChanging();
					this._DaNhac = value;
					this.SendPropertyChanged("DaNhac");
					this.OnDaNhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycYeuCau_tnycThongBao", Storage="_tnycYeuCau", ThisKey="MaYC", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public tnycYeuCau tnycYeuCau
		{
			get
			{
				return this._tnycYeuCau.Entity;
			}
			set
			{
				tnycYeuCau previousValue = this._tnycYeuCau.Entity;
				if (((previousValue != value) 
							|| (this._tnycYeuCau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tnycYeuCau.Entity = null;
						previousValue.tnycThongBaos.Remove(this);
					}
					this._tnycYeuCau.Entity = value;
					if ((value != null))
					{
						value.tnycThongBaos.Add(this);
						this._MaYC = value.ID;
					}
					else
					{
						this._MaYC = default(Nullable<int>);
					}
					this.SendPropertyChanged("tnycYeuCau");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycTrangThai")]
	public partial class tnycTrangThai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTT;
		
		private string _TenTT;
		
		private System.Nullable<int> _MauNen;
		
		private EntitySet<tnycLichSuCapNhat> _tnycLichSuCapNhats;
		
		private EntitySet<tnycYeuCau> _tnycYeuCaus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTChanging(int value);
    partial void OnMaTTChanged();
    partial void OnTenTTChanging(string value);
    partial void OnTenTTChanged();
    partial void OnMauNenChanging(System.Nullable<int> value);
    partial void OnMauNenChanged();
    #endregion
		
		public tnycTrangThai()
		{
			this._tnycLichSuCapNhats = new EntitySet<tnycLichSuCapNhat>(new Action<tnycLichSuCapNhat>(this.attach_tnycLichSuCapNhats), new Action<tnycLichSuCapNhat>(this.detach_tnycLichSuCapNhats));
			this._tnycYeuCaus = new EntitySet<tnycYeuCau>(new Action<tnycYeuCau>(this.attach_tnycYeuCaus), new Action<tnycYeuCau>(this.detach_tnycYeuCaus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTT", DbType="NVarChar(50)")]
		public string TenTT
		{
			get
			{
				return this._TenTT;
			}
			set
			{
				if ((this._TenTT != value))
				{
					this.OnTenTTChanging(value);
					this.SendPropertyChanging();
					this._TenTT = value;
					this.SendPropertyChanged("TenTT");
					this.OnTenTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauNen", DbType="Int")]
		public System.Nullable<int> MauNen
		{
			get
			{
				return this._MauNen;
			}
			set
			{
				if ((this._MauNen != value))
				{
					this.OnMauNenChanging(value);
					this.SendPropertyChanging();
					this._MauNen = value;
					this.SendPropertyChanged("MauNen");
					this.OnMauNenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycTrangThai_tnycLichSuCapNhat", Storage="_tnycLichSuCapNhats", ThisKey="MaTT", OtherKey="MaTT")]
		public EntitySet<tnycLichSuCapNhat> tnycLichSuCapNhats
		{
			get
			{
				return this._tnycLichSuCapNhats;
			}
			set
			{
				this._tnycLichSuCapNhats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycTrangThai_tnycYeuCau", Storage="_tnycYeuCaus", ThisKey="MaTT", OtherKey="MaTT")]
		public EntitySet<tnycYeuCau> tnycYeuCaus
		{
			get
			{
				return this._tnycYeuCaus;
			}
			set
			{
				this._tnycYeuCaus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tnycLichSuCapNhats(tnycLichSuCapNhat entity)
		{
			this.SendPropertyChanging();
			entity.tnycTrangThai = this;
		}
		
		private void detach_tnycLichSuCapNhats(tnycLichSuCapNhat entity)
		{
			this.SendPropertyChanging();
			entity.tnycTrangThai = null;
		}
		
		private void attach_tnycYeuCaus(tnycYeuCau entity)
		{
			this.SendPropertyChanging();
			entity.tnycTrangThai = this;
		}
		
		private void detach_tnycYeuCaus(tnycYeuCau entity)
		{
			this.SendPropertyChanging();
			entity.tnycTrangThai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tnycYeuCau")]
	public partial class tnycYeuCau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MaYC;
		
		private System.Nullable<System.DateTime> _NgayYC;
		
		private System.Nullable<int> _MaKH;
		
		private string _TieuDe;
		
		private string _NoiDung;
		
		private System.Nullable<int> _MaBP;
		
		private System.Nullable<int> _MaTT;
		
		private System.Nullable<int> _MaNV;
		
		private System.Nullable<byte> _MaTN;
		
		private System.Nullable<int> _MaNTN;
		
		private System.Nullable<int> _MaDoUuTien;
		
		private System.Nullable<int> _MaMB;
		
		private System.Nullable<int> _MaNguonDen;
		
		private System.Nullable<System.DateTime> _NgayHoanThanh;
		
		private string _NguoiGui;
		
		private System.Nullable<short> _SoYeuCau;
		
		private string _SoDienThoai;
		
		private System.Nullable<int> _MaLoaiYeuCau;
		
		private System.Nullable<System.DateTime> _TGKhachHen;
		
		private System.Nullable<bool> _IsNhanTho;
		
		private System.Nullable<System.DateTime> _NgayBanGiaoCH;
		
		private System.Nullable<System.DateTime> _NgayHetHanBH;
		
		private string _NVXuLy;
		
		private System.Nullable<System.DateTime> _NgayCN;
		
		private string _HinhAnh;
		
		private System.Nullable<System.DateTime> _NgayHetHanDauTien;
		
		private System.Nullable<System.DateTime> _NgayHetHanCuoiCung;
		
		private System.Nullable<int> _SoLanGiaHan;
		
		private System.Nullable<System.DateTime> _HanXuLyKhiGiaoViec;
		
		private System.Nullable<bool> _IsReadResident;
		
		private System.Nullable<bool> _IsReadVendor;
		
		private System.Nullable<decimal> _Rating;
		
		private string _RatingComment;
		
		private System.Nullable<System.DateTime> _RatingDate;
		
		private System.Nullable<int> _GroupProcessId;
		
		private EntitySet<tnycLichSuCapNhat> _tnycLichSuCapNhats;
		
		private EntitySet<tnycThongBao> _tnycThongBaos;
		
		private EntityRef<tnycDoUuTien> _tnycDoUuTien;
		
		private EntityRef<tnycNguonDen> _tnycNguonDen;
		
		private EntityRef<tnycTrangThai> _tnycTrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaYCChanging(string value);
    partial void OnMaYCChanged();
    partial void OnNgayYCChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayYCChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnMaBPChanging(System.Nullable<int> value);
    partial void OnMaBPChanged();
    partial void OnMaTTChanging(System.Nullable<int> value);
    partial void OnMaTTChanged();
    partial void OnMaNVChanging(System.Nullable<int> value);
    partial void OnMaNVChanged();
    partial void OnMaTNChanging(System.Nullable<byte> value);
    partial void OnMaTNChanged();
    partial void OnMaNTNChanging(System.Nullable<int> value);
    partial void OnMaNTNChanged();
    partial void OnMaDoUuTienChanging(System.Nullable<int> value);
    partial void OnMaDoUuTienChanged();
    partial void OnMaMBChanging(System.Nullable<int> value);
    partial void OnMaMBChanged();
    partial void OnMaNguonDenChanging(System.Nullable<int> value);
    partial void OnMaNguonDenChanged();
    partial void OnNgayHoanThanhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHoanThanhChanged();
    partial void OnNguoiGuiChanging(string value);
    partial void OnNguoiGuiChanged();
    partial void OnSoYeuCauChanging(System.Nullable<short> value);
    partial void OnSoYeuCauChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnMaLoaiYeuCauChanging(System.Nullable<int> value);
    partial void OnMaLoaiYeuCauChanged();
    partial void OnTGKhachHenChanging(System.Nullable<System.DateTime> value);
    partial void OnTGKhachHenChanged();
    partial void OnIsNhanThoChanging(System.Nullable<bool> value);
    partial void OnIsNhanThoChanged();
    partial void OnNgayBanGiaoCHChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBanGiaoCHChanged();
    partial void OnNgayHetHanBHChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanBHChanged();
    partial void OnNVXuLyChanging(string value);
    partial void OnNVXuLyChanged();
    partial void OnNgayCNChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCNChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnNgayHetHanDauTienChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanDauTienChanged();
    partial void OnNgayHetHanCuoiCungChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanCuoiCungChanged();
    partial void OnSoLanGiaHanChanging(System.Nullable<int> value);
    partial void OnSoLanGiaHanChanged();
    partial void OnHanXuLyKhiGiaoViecChanging(System.Nullable<System.DateTime> value);
    partial void OnHanXuLyKhiGiaoViecChanged();
    partial void OnIsReadResidentChanging(System.Nullable<bool> value);
    partial void OnIsReadResidentChanged();
    partial void OnIsReadVendorChanging(System.Nullable<bool> value);
    partial void OnIsReadVendorChanged();
    partial void OnRatingChanging(System.Nullable<decimal> value);
    partial void OnRatingChanged();
    partial void OnRatingCommentChanging(string value);
    partial void OnRatingCommentChanged();
    partial void OnRatingDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRatingDateChanged();
    partial void OnGroupProcessIdChanging(System.Nullable<int> value);
    partial void OnGroupProcessIdChanged();
    #endregion
		
		public tnycYeuCau()
		{
			this._tnycLichSuCapNhats = new EntitySet<tnycLichSuCapNhat>(new Action<tnycLichSuCapNhat>(this.attach_tnycLichSuCapNhats), new Action<tnycLichSuCapNhat>(this.detach_tnycLichSuCapNhats));
			this._tnycThongBaos = new EntitySet<tnycThongBao>(new Action<tnycThongBao>(this.attach_tnycThongBaos), new Action<tnycThongBao>(this.detach_tnycThongBaos));
			this._tnycDoUuTien = default(EntityRef<tnycDoUuTien>);
			this._tnycNguonDen = default(EntityRef<tnycNguonDen>);
			this._tnycTrangThai = default(EntityRef<tnycTrangThai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaYC", DbType="NVarChar(50)")]
		public string MaYC
		{
			get
			{
				return this._MaYC;
			}
			set
			{
				if ((this._MaYC != value))
				{
					this.OnMaYCChanging(value);
					this.SendPropertyChanging();
					this._MaYC = value;
					this.SendPropertyChanged("MaYC");
					this.OnMaYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayYC", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayYC
		{
			get
			{
				return this._NgayYC;
			}
			set
			{
				if ((this._NgayYC != value))
				{
					this.OnNgayYCChanging(value);
					this.SendPropertyChanging();
					this._NgayYC = value;
					this.SendPropertyChanged("NgayYC");
					this.OnNgayYCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(150)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBP", DbType="Int")]
		public System.Nullable<int> MaBP
		{
			get
			{
				return this._MaBP;
			}
			set
			{
				if ((this._MaBP != value))
				{
					this.OnMaBPChanging(value);
					this.SendPropertyChanging();
					this._MaBP = value;
					this.SendPropertyChanged("MaBP");
					this.OnMaBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="Int")]
		public System.Nullable<int> MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					if (this._tnycTrangThai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int")]
		public System.Nullable<int> MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTN", DbType="TinyInt")]
		public System.Nullable<byte> MaTN
		{
			get
			{
				return this._MaTN;
			}
			set
			{
				if ((this._MaTN != value))
				{
					this.OnMaTNChanging(value);
					this.SendPropertyChanging();
					this._MaTN = value;
					this.SendPropertyChanged("MaTN");
					this.OnMaTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNTN", DbType="Int")]
		public System.Nullable<int> MaNTN
		{
			get
			{
				return this._MaNTN;
			}
			set
			{
				if ((this._MaNTN != value))
				{
					this.OnMaNTNChanging(value);
					this.SendPropertyChanging();
					this._MaNTN = value;
					this.SendPropertyChanged("MaNTN");
					this.OnMaNTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoUuTien", DbType="Int")]
		public System.Nullable<int> MaDoUuTien
		{
			get
			{
				return this._MaDoUuTien;
			}
			set
			{
				if ((this._MaDoUuTien != value))
				{
					if (this._tnycDoUuTien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoUuTienChanging(value);
					this.SendPropertyChanging();
					this._MaDoUuTien = value;
					this.SendPropertyChanged("MaDoUuTien");
					this.OnMaDoUuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMB", DbType="Int")]
		public System.Nullable<int> MaMB
		{
			get
			{
				return this._MaMB;
			}
			set
			{
				if ((this._MaMB != value))
				{
					this.OnMaMBChanging(value);
					this.SendPropertyChanging();
					this._MaMB = value;
					this.SendPropertyChanged("MaMB");
					this.OnMaMBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguonDen", DbType="Int")]
		public System.Nullable<int> MaNguonDen
		{
			get
			{
				return this._MaNguonDen;
			}
			set
			{
				if ((this._MaNguonDen != value))
				{
					if (this._tnycNguonDen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguonDenChanging(value);
					this.SendPropertyChanging();
					this._MaNguonDen = value;
					this.SendPropertyChanged("MaNguonDen");
					this.OnMaNguonDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHoanThanh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHoanThanh
		{
			get
			{
				return this._NgayHoanThanh;
			}
			set
			{
				if ((this._NgayHoanThanh != value))
				{
					this.OnNgayHoanThanhChanging(value);
					this.SendPropertyChanging();
					this._NgayHoanThanh = value;
					this.SendPropertyChanged("NgayHoanThanh");
					this.OnNgayHoanThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiGui", DbType="NVarChar(200)")]
		public string NguoiGui
		{
			get
			{
				return this._NguoiGui;
			}
			set
			{
				if ((this._NguoiGui != value))
				{
					this.OnNguoiGuiChanging(value);
					this.SendPropertyChanging();
					this._NguoiGui = value;
					this.SendPropertyChanged("NguoiGui");
					this.OnNguoiGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoYeuCau", DbType="SmallInt")]
		public System.Nullable<short> SoYeuCau
		{
			get
			{
				return this._SoYeuCau;
			}
			set
			{
				if ((this._SoYeuCau != value))
				{
					this.OnSoYeuCauChanging(value);
					this.SendPropertyChanging();
					this._SoYeuCau = value;
					this.SendPropertyChanged("SoYeuCau");
					this.OnSoYeuCauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(20)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiYeuCau", DbType="Int")]
		public System.Nullable<int> MaLoaiYeuCau
		{
			get
			{
				return this._MaLoaiYeuCau;
			}
			set
			{
				if ((this._MaLoaiYeuCau != value))
				{
					this.OnMaLoaiYeuCauChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiYeuCau = value;
					this.SendPropertyChanged("MaLoaiYeuCau");
					this.OnMaLoaiYeuCauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGKhachHen", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGKhachHen
		{
			get
			{
				return this._TGKhachHen;
			}
			set
			{
				if ((this._TGKhachHen != value))
				{
					this.OnTGKhachHenChanging(value);
					this.SendPropertyChanging();
					this._TGKhachHen = value;
					this.SendPropertyChanged("TGKhachHen");
					this.OnTGKhachHenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNhanTho", DbType="Bit")]
		public System.Nullable<bool> IsNhanTho
		{
			get
			{
				return this._IsNhanTho;
			}
			set
			{
				if ((this._IsNhanTho != value))
				{
					this.OnIsNhanThoChanging(value);
					this.SendPropertyChanging();
					this._IsNhanTho = value;
					this.SendPropertyChanged("IsNhanTho");
					this.OnIsNhanThoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBanGiaoCH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBanGiaoCH
		{
			get
			{
				return this._NgayBanGiaoCH;
			}
			set
			{
				if ((this._NgayBanGiaoCH != value))
				{
					this.OnNgayBanGiaoCHChanging(value);
					this.SendPropertyChanging();
					this._NgayBanGiaoCH = value;
					this.SendPropertyChanged("NgayBanGiaoCH");
					this.OnNgayBanGiaoCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHanBH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHanBH
		{
			get
			{
				return this._NgayHetHanBH;
			}
			set
			{
				if ((this._NgayHetHanBH != value))
				{
					this.OnNgayHetHanBHChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHanBH = value;
					this.SendPropertyChanged("NgayHetHanBH");
					this.OnNgayHetHanBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NVXuLy", DbType="NVarChar(500)")]
		public string NVXuLy
		{
			get
			{
				return this._NVXuLy;
			}
			set
			{
				if ((this._NVXuLy != value))
				{
					this.OnNVXuLyChanging(value);
					this.SendPropertyChanging();
					this._NVXuLy = value;
					this.SendPropertyChanged("NVXuLy");
					this.OnNVXuLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCN
		{
			get
			{
				return this._NgayCN;
			}
			set
			{
				if ((this._NgayCN != value))
				{
					this.OnNgayCNChanging(value);
					this.SendPropertyChanging();
					this._NgayCN = value;
					this.SendPropertyChanged("NgayCN");
					this.OnNgayCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(300)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHanDauTien", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHanDauTien
		{
			get
			{
				return this._NgayHetHanDauTien;
			}
			set
			{
				if ((this._NgayHetHanDauTien != value))
				{
					this.OnNgayHetHanDauTienChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHanDauTien = value;
					this.SendPropertyChanged("NgayHetHanDauTien");
					this.OnNgayHetHanDauTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHanCuoiCung", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHanCuoiCung
		{
			get
			{
				return this._NgayHetHanCuoiCung;
			}
			set
			{
				if ((this._NgayHetHanCuoiCung != value))
				{
					this.OnNgayHetHanCuoiCungChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHanCuoiCung = value;
					this.SendPropertyChanged("NgayHetHanCuoiCung");
					this.OnNgayHetHanCuoiCungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanGiaHan", DbType="Int")]
		public System.Nullable<int> SoLanGiaHan
		{
			get
			{
				return this._SoLanGiaHan;
			}
			set
			{
				if ((this._SoLanGiaHan != value))
				{
					this.OnSoLanGiaHanChanging(value);
					this.SendPropertyChanging();
					this._SoLanGiaHan = value;
					this.SendPropertyChanged("SoLanGiaHan");
					this.OnSoLanGiaHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanXuLyKhiGiaoViec", DbType="DateTime")]
		public System.Nullable<System.DateTime> HanXuLyKhiGiaoViec
		{
			get
			{
				return this._HanXuLyKhiGiaoViec;
			}
			set
			{
				if ((this._HanXuLyKhiGiaoViec != value))
				{
					this.OnHanXuLyKhiGiaoViecChanging(value);
					this.SendPropertyChanging();
					this._HanXuLyKhiGiaoViec = value;
					this.SendPropertyChanged("HanXuLyKhiGiaoViec");
					this.OnHanXuLyKhiGiaoViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReadResident", DbType="Bit")]
		public System.Nullable<bool> IsReadResident
		{
			get
			{
				return this._IsReadResident;
			}
			set
			{
				if ((this._IsReadResident != value))
				{
					this.OnIsReadResidentChanging(value);
					this.SendPropertyChanging();
					this._IsReadResident = value;
					this.SendPropertyChanged("IsReadResident");
					this.OnIsReadResidentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReadVendor", DbType="Bit")]
		public System.Nullable<bool> IsReadVendor
		{
			get
			{
				return this._IsReadVendor;
			}
			set
			{
				if ((this._IsReadVendor != value))
				{
					this.OnIsReadVendorChanging(value);
					this.SendPropertyChanging();
					this._IsReadVendor = value;
					this.SendPropertyChanged("IsReadVendor");
					this.OnIsReadVendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RatingComment", DbType="NVarChar(500)")]
		public string RatingComment
		{
			get
			{
				return this._RatingComment;
			}
			set
			{
				if ((this._RatingComment != value))
				{
					this.OnRatingCommentChanging(value);
					this.SendPropertyChanging();
					this._RatingComment = value;
					this.SendPropertyChanged("RatingComment");
					this.OnRatingCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RatingDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RatingDate
		{
			get
			{
				return this._RatingDate;
			}
			set
			{
				if ((this._RatingDate != value))
				{
					this.OnRatingDateChanging(value);
					this.SendPropertyChanging();
					this._RatingDate = value;
					this.SendPropertyChanged("RatingDate");
					this.OnRatingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupProcessId", DbType="Int")]
		public System.Nullable<int> GroupProcessId
		{
			get
			{
				return this._GroupProcessId;
			}
			set
			{
				if ((this._GroupProcessId != value))
				{
					this.OnGroupProcessIdChanging(value);
					this.SendPropertyChanging();
					this._GroupProcessId = value;
					this.SendPropertyChanged("GroupProcessId");
					this.OnGroupProcessIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycYeuCau_tnycLichSuCapNhat", Storage="_tnycLichSuCapNhats", ThisKey="ID", OtherKey="MaYC")]
		public EntitySet<tnycLichSuCapNhat> tnycLichSuCapNhats
		{
			get
			{
				return this._tnycLichSuCapNhats;
			}
			set
			{
				this._tnycLichSuCapNhats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycYeuCau_tnycThongBao", Storage="_tnycThongBaos", ThisKey="ID", OtherKey="MaYC")]
		public EntitySet<tnycThongBao> tnycThongBaos
		{
			get
			{
				return this._tnycThongBaos;
			}
			set
			{
				this._tnycThongBaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycDoUuTien_tnycYeuCau", Storage="_tnycDoUuTien", ThisKey="MaDoUuTien", OtherKey="MaDoUuTien", IsForeignKey=true)]
		public tnycDoUuTien tnycDoUuTien
		{
			get
			{
				return this._tnycDoUuTien.Entity;
			}
			set
			{
				tnycDoUuTien previousValue = this._tnycDoUuTien.Entity;
				if (((previousValue != value) 
							|| (this._tnycDoUuTien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tnycDoUuTien.Entity = null;
						previousValue.tnycYeuCaus.Remove(this);
					}
					this._tnycDoUuTien.Entity = value;
					if ((value != null))
					{
						value.tnycYeuCaus.Add(this);
						this._MaDoUuTien = value.MaDoUuTien;
					}
					else
					{
						this._MaDoUuTien = default(Nullable<int>);
					}
					this.SendPropertyChanged("tnycDoUuTien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycNguonDen_tnycYeuCau", Storage="_tnycNguonDen", ThisKey="MaNguonDen", OtherKey="ID", IsForeignKey=true)]
		public tnycNguonDen tnycNguonDen
		{
			get
			{
				return this._tnycNguonDen.Entity;
			}
			set
			{
				tnycNguonDen previousValue = this._tnycNguonDen.Entity;
				if (((previousValue != value) 
							|| (this._tnycNguonDen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tnycNguonDen.Entity = null;
						previousValue.tnycYeuCaus.Remove(this);
					}
					this._tnycNguonDen.Entity = value;
					if ((value != null))
					{
						value.tnycYeuCaus.Add(this);
						this._MaNguonDen = value.ID;
					}
					else
					{
						this._MaNguonDen = default(Nullable<int>);
					}
					this.SendPropertyChanged("tnycNguonDen");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tnycTrangThai_tnycYeuCau", Storage="_tnycTrangThai", ThisKey="MaTT", OtherKey="MaTT", IsForeignKey=true)]
		public tnycTrangThai tnycTrangThai
		{
			get
			{
				return this._tnycTrangThai.Entity;
			}
			set
			{
				tnycTrangThai previousValue = this._tnycTrangThai.Entity;
				if (((previousValue != value) 
							|| (this._tnycTrangThai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tnycTrangThai.Entity = null;
						previousValue.tnycYeuCaus.Remove(this);
					}
					this._tnycTrangThai.Entity = value;
					if ((value != null))
					{
						value.tnycYeuCaus.Add(this);
						this._MaTT = value.MaTT;
					}
					else
					{
						this._MaTT = default(Nullable<int>);
					}
					this.SendPropertyChanged("tnycTrangThai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tnycLichSuCapNhats(tnycLichSuCapNhat entity)
		{
			this.SendPropertyChanging();
			entity.tnycYeuCau = this;
		}
		
		private void detach_tnycLichSuCapNhats(tnycLichSuCapNhat entity)
		{
			this.SendPropertyChanging();
			entity.tnycYeuCau = null;
		}
		
		private void attach_tnycThongBaos(tnycThongBao entity)
		{
			this.SendPropertyChanging();
			entity.tnycYeuCau = this;
		}
		
		private void detach_tnycThongBaos(tnycThongBao entity)
		{
			this.SendPropertyChanging();
			entity.tnycYeuCau = null;
		}
	}
}
#pragma warning restore 1591
